// templates/nextjs/frontend/src/app/auth/oauth/page.tsx
import Link from 'next/link';
import { signInDestination } from '@/app/signin/destination';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { appOrigin } from '@/lib/nhost/env';
import { createNhostClient } from '@/lib/nhost/server';
import OAuthButtons from './OAuthButtons';
import { providers } from './providers';

export const dynamic = 'force-dynamic';

/**
 * Sign in with a provider account.
 *
 * This is a redirect, not a request: each button sends the browser to the auth
 * service, which does the provider round-trip and comes back to `redirectTo`
 * with a refresh token on the URL. The proxy redeems that token (see
 * `lib/nhost/server.ts`), so this page never sees the callback.
 */
export default async function OAuth({
  searchParams,
}: {
  searchParams: Promise<{ next?: string | string[] }>;
}) {
  const { next } = await searchParams;
  const destination = signInDestination(next);

  const nhost = await createNhostClient();
  const links = providers.map(({ id, label }) => ({
    id,
    label,
    href: nhost.auth.signInProviderURL(id, {
      redirectTo: appOrigin() + destination,
    }),
  }));

  return (
    <div className="mx-auto max-w-md">
      <Card>
        <CardHeader>
          <CardTitle>GitHub or Google</CardTitle>
          <CardDescription>Sign in with a provider account.</CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-4">
          <OAuthButtons links={links} />
          <p className="text-muted-foreground text-sm">
            A provider only works once it is enabled in <code>nhost.toml</code>.
            The README&apos;s OAuth section has the callback URL and the config.
          </p>
          <Link
            href="/signin"
            className="text-muted-foreground text-sm underline-offset-4 hover:underline"
          >
            Other ways to sign in
          </Link>
        </CardContent>
      </Card>
    </div>
  );
}

// templates/svelte/frontend/src/routes/auth/oauth/+page.svelte
<script lang="ts">
import * as Card from '$lib/components/ui/card';
import { useAuth } from '$lib/nhost/auth.svelte';
import { appOrigin } from '$lib/nhost/env';
import { nextDestination } from '$lib/signin/next';
import OAuthButtons from './OAuthButtons.svelte';
import { providers } from './providers';

/**
 * Sign in with a provider account.
 *
 * This is a redirect, not a request: each button sends the browser to the
 * auth service, which does the provider round-trip and comes back to
 * `redirectTo` with a refresh token on the URL. That token is redeemed by
 * `lib/nhost/linkToken.ts` when the app loads again, so this page never sees
 * the callback.
 */
const auth = useAuth();
const next = $derived(nextDestination());

const links = $derived(
  providers.map(({ id, label }) => ({
    id,
    label,
    href: auth.nhost.auth.signInProviderURL(id, {
      redirectTo: appOrigin() + next,
    }),
  })),
);
</script>

<div class="mx-auto max-w-md">
  <Card.Root>
    <Card.Header>
      <Card.Title>GitHub or Google</Card.Title>
      <Card.Description>Sign in with a provider account.</Card.Description>
    </Card.Header>
    <Card.Content class="flex flex-col gap-4">
      <OAuthButtons {links} />
      <p class="text-muted-foreground text-sm">
        A provider only works once it is enabled in <code>nhost.toml</code>. The
        README's OAuth section has the callback URL and the config.
      </p>
      <a
        href="/signin"
        class="text-muted-foreground text-sm underline-offset-4 hover:underline"
      >
        Other ways to sign in
      </a>
    </Card.Content>
  </Card.Root>
</div>
