// examples/tutorials/nhost-vue-tutorial/src/views/SignUp.vue
<template>
  <div>
    <h1 v-if="!success">Sign Up</h1>
    <h1 v-else>Check Your Email</h1>

    <div v-if="success" class="success-message">
      <p>
        We've sent a verification link to <strong>{{ email }}</strong>
      </p>
      <p>
        Please check your email and click the verification link to activate your account.
      </p>
      <p>
        <router-link to="/signin">Back to Sign In</router-link>
      </p>
    </div>

    <form v-else @submit.prevent="handleSubmit" class="auth-form">
      <div class="auth-form-field">
        <label :for="displayNameId">Display Name</label>
        <input
          :id="displayNameId"
          type="text"
          v-model="displayName"
          required
          class="auth-input"
        />
      </div>

      <div class="auth-form-field">
        <label :for="emailId">Email</label>
        <input
          :id="emailId"
          type="email"
          v-model="email"
          required
          class="auth-input"
        />
      </div>

      <div class="auth-form-field">
        <label :for="passwordId">Password</label>
        <input
          :id="passwordId"
          type="password"
          v-model="password"
          required
          minlength="8"
          class="auth-input"
        />
        <small class="help-text">Minimum 8 characters</small>
      </div>

      <div v-if="error" class="auth-error">
        {{ error }}
      </div>

      <button
        type="submit"
        :disabled="isLoading"
        class="auth-button primary"
      >
        {{ isLoading ? "Creating Account..." : "Sign Up" }}
      </button>
    </form>

    <div v-if="!success" class="auth-links">
      <p>
        Already have an account? <router-link to="/signin">Sign In</router-link>
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { generatePKCEPair } from '@nhost/nhost-js/auth';
import { onMounted, ref, useId } from 'vue';
import { useRouter } from 'vue-router';
import { useAuth } from '../lib/nhost/auth';

const { nhost, isAuthenticated } = useAuth();
const router = useRouter();

const email = ref('');
const password = ref('');
const displayName = ref('');
const isLoading = ref(false);
const error = ref<string | null>(null);
const success = ref(false);

const displayNameId = useId();
const emailId = useId();
const passwordId = useId();

// Redirect authenticated users to profile
onMounted(() => {
  if (isAuthenticated.value) {
    router.push('/profile');
  }
});

const handleSubmit = async () => {
  isLoading.value = true;
  error.value = null;
  success.value = false;

  try {
    // Generate PKCE pair and store verifier for email verification
    const { verifier, challenge } = await generatePKCEPair();
    localStorage.setItem('nhost_pkce_verifier', verifier);

    const response = await nhost.auth.signUpEmailPassword({
      email: email.value,
      password: password.value,
      options: {
        displayName: displayName.value,
        redirectTo: `${window.location.origin}/verify`,
      },
      codeChallenge: challenge,
    });

    if (response.body?.session) {
      // Successfully signed up and automatically signed in
      router.push('/profile');
    } else {
      // Verification email sent
      success.value = true;
    }
  } catch (err) {
    const message = (err as Error).message || 'Unknown error';
    error.value = `An error occurred during sign up: ${message}`;
  } finally {
    isLoading.value = false;
  }
};
</script>

// examples/tutorials/nhost-react-tutorial/src/pages/SignUp.tsx
import { generatePKCEPair } from '@nhost/nhost-js/auth';
import { useEffect, useId, useState } from 'react';
import { Link, useNavigate } from 'react-router';
import { useAuth } from '../lib/nhost/AuthProvider';

export default function SignUp() {
  const { nhost, isAuthenticated } = useAuth();
  const navigate = useNavigate();

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);
  const displayNameId = useId();

  const emailId = useId();
  const passwordId = useId();

  // Redirect authenticated users to profile
  useEffect(() => {
    if (isAuthenticated) {
      navigate('/profile');
    }
  }, [isAuthenticated, navigate]);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);
    setSuccess(false);

    try {
      // Generate PKCE pair and store verifier for email verification
      const { verifier, challenge } = await generatePKCEPair();
      localStorage.setItem('nhost_pkce_verifier', verifier);

      const response = await nhost.auth.signUpEmailPassword({
        email,
        password,
        options: {
          displayName,
          redirectTo: `${window.location.origin}/verify`,
        },
        codeChallenge: challenge,
      });

      if (response.body?.session) {
        // Successfully signed up and automatically signed in
        navigate('/profile');
      } else {
        // Verification email sent
        setSuccess(true);
      }
    } catch (err) {
      const message = (err as Error).message || 'Unknown error';
      setError(`An error occurred during sign up: ${message}`);
    } finally {
      setIsLoading(false);
    }
  };

  if (success) {
    return (
      <div>
        <h1>Check Your Email</h1>
        <div className="success-message">
          <p>
            We've sent a verification link to <strong>{email}</strong>
          </p>
          <p>
            Please check your email and click the verification link to activate
            your account.
          </p>
        </div>
        <p>
          <Link to="/signin">Back to Sign In</Link>
        </p>
      </div>
    );
  }

  return (
    <div>
      <h1>Sign Up</h1>

      <form onSubmit={handleSubmit} className="auth-form">
        <div className="auth-form-field">
          <label htmlFor={displayNameId}>Display Name</label>
          <input
            id={displayNameId}
            type="text"
            value={displayName}
            onChange={(e) => setDisplayName(e.target.value)}
            required
            className="auth-input"
          />
        </div>

        <div className="auth-form-field">
          <label htmlFor={emailId}>Email</label>
          <input
            id={emailId}
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
            className="auth-input"
          />
        </div>

        <div className="auth-form-field">
          <label htmlFor={passwordId}>Password</label>
          <input
            id={passwordId}
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            minLength={8}
            className="auth-input"
          />
          <small className="help-text">Minimum 8 characters</small>
        </div>

        {error && <div className="auth-error">{error}</div>}

        <button
          type="submit"
          disabled={isLoading}
          className={`auth-button primary`}
        >
          {isLoading ? 'Creating Account...' : 'Sign Up'}
        </button>
      </form>

      <div className="auth-links">
        <p>
          Already have an account? <Link to="/signin">Sign In</Link>
        </p>
      </div>
    </div>
  );
}
