// deprecated/examples/quickstarts/sveltekit/src/routes/auth/sign-up/email-password/+page.svelte
<script>
	import Button from '$lib/components/Button.svelte'
	import Input from '$lib/components/Input.svelte'

	/** @type {import('./$types').Actions} */
	export let form;
</script>

<svelte:head>
	<title>Sign Up</title>
</svelte:head>

<h1 class="text-2xl font-semibold text-center">Sign Up</h1>

{#if form?.error}
	<p class="mt-3 font-semibold text-center text-red-500">{form?.error}</p>
{/if}

<div class='max-w-xl mx-auto'>
	<form class="space-y-5" method='POST'>
		<Input
			label="First Name"
			id="firstName"
			name="firstName"
			type="text"
			required
		/>
	
		<Input
			label="Last Name"
			id="lastName"
			name="lastName"
			type="text"
			required
		/>
	
		<Input label="Email" id="email" name="email" type="email" required />
	
		<Input
			label="Password"
			id="password"
			name="password"
			type="password"
			required
		/>
	
		<Button class='block w-full' type="submit">Sign Up</Button>
	</form>
</div>

// examples/quickstarts/nextjs-server-components/src/app/auth/sign-up/email-password/page.tsx
'use client'

import { signUp } from '@actions'
import Input from '@components/input'
import SubmitButton from '@components/submit-button'
import { useState } from 'react'

export default function SignUpWithEmailAndPassword() {
  const [error, setError] = useState('')

  async function handleSignUp(formData: FormData) {
    const response = await signUp(formData)

    if (response?.error) {
      setError(response.error)
    }
  }

  return (
    <>
      <h1 className="text-2xl font-semibold text-center">Sign Up</h1>

      {error && <p className="mt-3 font-semibold text-center text-red-500">{error}</p>}

      <form className="space-y-5" action={handleSignUp}>
        <Input label="First Name" id="firstName" name="firstName" required />
        <Input label="Last Name" id="lastName" name="lastName" required />
        <Input label="Email" id="email" name="email" type="email" required />
        <Input label="Password" id="password" name="password" type="password" required />
        <SubmitButton type="submit">Sign Up</SubmitButton>
      </form>
    </>
  )
}
