// templates/react-native/frontend/src/components/SignOutButton.tsx
import { useState } from 'react';
import { View } from 'react-native';
import { Button } from '@/components/ui/Button';
import { ErrorText } from '@/components/ui/ErrorText';
import { useGo } from '@/lib/navigation';
import { useAuth } from '@/lib/nhost/AuthProvider';

export function SignOutButton() {
  const { nhost } = useAuth();
  const go = useGo();

  const [error, setError] = useState<string | undefined>();
  const [isSigningOut, setIsSigningOut] = useState(false);

  const handleSignOut = async (): Promise<void> => {
    setError(undefined);
    setIsSigningOut(true);
    try {
      // Clears the stored session, which the provider is subscribed to, so
      // every screen drops to signed out without this having to tell them.
      await nhost.auth.signOut({
        refreshToken: nhost.getUserSession()?.refreshToken ?? '',
      });

      go.replace('/');
    } catch (err) {
      console.error('Error signing out:', err);
      setError('The request did not reach the server. Try again.');
    } finally {
      setIsSigningOut(false);
    }
  };

  return (
    <View className="gap-1">
      <Button
        variant="outline"
        isPending={isSigningOut}
        onPress={() => void handleSignOut()}
      >
        {isSigningOut ? 'Signing out…' : 'Sign out'}
      </Button>
      {error ? <ErrorText>{error}</ErrorText> : null}
    </View>
  );
}

// templates/svelte/frontend/src/lib/components/SignOutButton.svelte
<script lang="ts">
import { goto } from '$app/navigation';
import { Button } from '$lib/components/ui/button';
import { useAuth } from '$lib/nhost/auth.svelte';

const auth = useAuth();

let error = $state<string | undefined>();
let isSigningOut = $state(false);

async function handleSignOut(): Promise<void> {
  error = undefined;
  isSigningOut = true;
  try {
    // Clears the stored session, which the storage subscription in
    // `lib/nhost/auth.svelte.ts` is listening to, so every tab drops to
    // signed out without this having to tell them.
    await auth.nhost.auth.signOut({
      refreshToken: auth.nhost.getUserSession()?.refreshToken ?? '',
    });

    await goto('/');
  } catch (err) {
    console.error('Error signing out:', err);
    error = 'The request did not reach the server. Try again.';
  } finally {
    isSigningOut = false;
  }
}
</script>

<div class="flex flex-col items-end gap-1">
  <Button
    type="button"
    variant="outline"
    size="sm"
    disabled={isSigningOut}
    onclick={handleSignOut}
  >
    {isSigningOut ? 'Signing out…' : 'Sign out'}
  </Button>
  {#if error}
    <p role="alert" class="text-destructive text-sm">{error}</p>
  {/if}
</div>
