// templates/svelte/frontend/src/routes/auth/otp/+page.svelte
<script lang="ts">
import * as Card from '$lib/components/ui/card';
import { localMailboxURL } from '$lib/nhost/env';
import { nextDestination } from '$lib/signin/next';
import OtpForm from './OtpForm.svelte';

const next = $derived(nextDestination());
const mailboxUrl = localMailboxURL();
</script>

<div class="mx-auto max-w-md">
  <Card.Root>
    <Card.Header>
      <Card.Title>Email code</Card.Title>
      <Card.Description>
        We email you a one-time code and you type it in here.
      </Card.Description>
    </Card.Header>
    <Card.Content class="flex flex-col gap-4">
      <OtpForm {next} {mailboxUrl} />
      <a
        href="/signin"
        class="text-muted-foreground text-sm underline underline-offset-4"
      >
        Other ways to sign in
      </a>
    </Card.Content>
  </Card.Root>
</div>

// templates/nextjs/frontend/src/app/auth/otp/page.tsx
import Link from 'next/link';
import { signInDestination } from '@/app/signin/destination';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { localMailboxURL } from '@/lib/nhost/env';
import OtpForm from './OtpForm';

export const dynamic = 'force-dynamic';

export default async function OtpSignIn({
  searchParams,
}: {
  searchParams: Promise<{ next?: string | string[] }>;
}) {
  const { next } = await searchParams;
  const destination = signInDestination(next);

  return (
    <div className="mx-auto max-w-md">
      <Card>
        <CardHeader>
          <CardTitle>Email code</CardTitle>
          <CardDescription>
            We email you a one-time code and you type it in here.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-4">
          <OtpForm next={destination} mailboxURL={localMailboxURL()} />
          <Link
            href="/signin"
            className="text-muted-foreground text-sm underline underline-offset-4"
          >
            Other ways to sign in
          </Link>
        </CardContent>
      </Card>
    </div>
  );
}
