// templates/vue/frontend/src/components/LinkErrorNotice.vue
<script setup lang="ts">
import { onUnmounted } from 'vue';
import { START_LOCATION, useRouter } from 'vue-router';
import { useAuth } from '@/lib/nhost/auth';

/**
 * Says why the link or provider redirect the visitor arrived from did not
 * sign them in. It sits above every page because that can be any of them: an
 * auth email or a provider comes back to wherever `next` said.
 *
 * It goes once the visitor moves on, except to sign-in: that is where trying
 * again starts, and where a protected page sends someone the link did not
 * sign in, so the reason still applies there.
 */
const { linkError, clearLinkError } = useAuth();

const stopListening = useRouter().afterEach((to, from, failure) => {
  if (
    !failure &&
    from !== START_LOCATION &&
    to.path !== from.path &&
    to.path !== '/signin'
  ) {
    clearLinkError();
  }
});

onUnmounted(stopListening);
</script>

<template>
  <p
    v-if="linkError"
    role="alert"
    class="mx-auto mb-6 max-w-md text-destructive text-sm"
  >
    {{ linkError }}
  </p>
</template>

// templates/react/frontend/src/components/LinkErrorNotice.tsx
import { useEffect, useRef } from 'react';
import { NavigationType, useLocation, useNavigationType } from 'react-router';
import { useAuth } from '@/lib/nhost/AuthProvider';

/**
 * Says why the link or provider redirect the visitor arrived from did not
 * sign them in. It sits above every page because that can be any of them: an
 * auth email or a provider comes back to wherever `next` said.
 *
 * It belongs to the page the visitor arrived on and goes once they move on. A
 * protected page's redirect to sign-in replaces that page rather than leaving
 * it, so the reason follows them there.
 */
export default function LinkErrorNotice() {
  const { linkError, clearLinkError } = useAuth();
  const { key } = useLocation();
  const navigationType = useNavigationType();
  const arrival = useRef(key);

  useEffect(() => {
    if (key !== arrival.current && navigationType !== NavigationType.Replace) {
      clearLinkError();
    }
  }, [key, navigationType, clearLinkError]);

  if (!linkError) {
    return null;
  }

  return (
    <p role="alert" className="mx-auto mb-6 max-w-md text-destructive text-sm">
      {linkError}
    </p>
  );
}
