// templates/react-apollo/src/components/routes/auth/verify-email.tsx
import { useNhostClient } from '@nhost/react'
import { useSearchParams } from 'react-router-dom'
import { toast } from 'sonner'

export default function VerifyEmail() {
  const nhost = useNhostClient()
  const [searchParams] = useSearchParams()

  const redirectToVerificationLink = () => {
    const ticket = searchParams.get('ticket')
    const type = searchParams.get('type')
    const redirectTo = searchParams.get('redirectTo')

    if (ticket && type && redirectTo) {
      window.location.href = `${nhost.auth.url}/verify?ticket=${ticket}&type=${type}&redirectTo=${redirectTo}`
    } else {
      toast.error('An error occured while verifying your account')
    }
  }

  return <div></div>

  return (
    <div>
      <Card shadow="sm" p="lg" radius="md" withBorder>
        <Stack align="center">
          <Text>Please verify your account by clicking the link below.</Text>
          <Button leftIcon={<FaEnvelope size={14} />} onClick={redirectToVerificationLink}>
            Verify
          </Button>
        </Stack>
      </Card>
    </div>
  )
}

// deprecated/examples/vue-apollo/src/pages/VerifyEmail.vue
<template>
  <div className="d-flex align-center flex-column">
    <v-card width="400" v-if="!loading">
      <v-card-text>Failed to authenticate with magick link</v-card-text>
    </v-card>
  </div>
</template>

<script lang="ts" setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useNhostClient } from '@nhost/vue'

const { nhost } = useNhostClient()
const route = useRoute()

const loading = ref(true)

onMounted(() => {
  const ticket = route.query.ticket
  const redirectTo = route.query.redirectTo
  const type = route.query.type

  if (ticket && redirectTo && type) {
    window.location.href = `${nhost.auth.url}/verify?ticket=${ticket}&type=${type}&redirectTo=${redirectTo}`
  }

  loading.value = false
})
</script>
