// examples/demos/react-demo/src/components/TabForm.tsx
import { type JSX, type ReactNode, useState } from "react";

interface TabFormProps {
  passwordTabContent: ReactNode;
  magicTabContent: ReactNode;
  socialTabContent?: ReactNode;
  webauthnTabContent?: ReactNode;
}

export default function TabForm({
  passwordTabContent,
  magicTabContent,
  socialTabContent,
  webauthnTabContent,
}: TabFormProps): JSX.Element {
  const [activeTab, setActiveTab] = useState<
    "password" | "magic" | "social" | "webauthn"
  >("password");

  return (
    <div>
      <div className="tabs-container">
        <button
          type="button"
          className={`tab-button ${activeTab === "password" ? "tab-active" : ""}`}
          onClick={() => setActiveTab("password")}
        >
          Email + Password
        </button>
        <button
          type="button"
          className={`tab-button ${activeTab === "magic" ? "tab-active" : ""}`}
          onClick={() => setActiveTab("magic")}
        >
          Magic Link
        </button>
        {socialTabContent && (
          <button
            type="button"
            className={`tab-button ${activeTab === "social" ? "tab-active" : ""}`}
            onClick={() => setActiveTab("social")}
          >
            Social
          </button>
        )}
        {webauthnTabContent && (
          <button
            type="button"
            className={`tab-button ${activeTab === "webauthn" ? "tab-active" : ""}`}
            onClick={() => setActiveTab("webauthn")}
          >
            Security Key
          </button>
        )}
      </div>

      <div className="tab-content">
        {activeTab === "password"
          ? passwordTabContent
          : activeTab === "magic"
            ? magicTabContent
            : activeTab === "social"
              ? socialTabContent
              : webauthnTabContent}
      </div>
    </div>
  );
}

// examples/demos/sveltekit-demo/src/lib/components/TabForm.svelte
<script lang="ts">
import type { Snippet } from "svelte";

interface Props {
  passwordTabContent: Snippet;
  magicTabContent: Snippet;
  socialTabContent?: Snippet;
  webauthnTabContent?: Snippet;
}

let {
  passwordTabContent,
  magicTabContent,
  socialTabContent,
  webauthnTabContent,
}: Props = $props();

let activeTab: "password" | "magic" | "social" | "webauthn" =
  $state("password");
</script>

<div>
  <div class="tabs-container">
    <button
      class="tab-button {activeTab === 'password' ? 'tab-active' : ''}"
      onclick={() => (activeTab = "password")}
    >
      Email + Password
    </button>
    <button
      class="tab-button {activeTab === 'magic' ? 'tab-active' : ''}"
      onclick={() => (activeTab = "magic")}
    >
      Magic Link
    </button>
    {#if socialTabContent}
      <button
        class="tab-button {activeTab === 'social' ? 'tab-active' : ''}"
        onclick={() => (activeTab = "social")}
      >
        Social
      </button>
    {/if}
    {#if webauthnTabContent}
      <button
        class="tab-button {activeTab === 'webauthn' ? 'tab-active' : ''}"
        onclick={() => (activeTab = "webauthn")}
      >
        Security Key
      </button>
    {/if}
  </div>

  <div class="tab-content">
    {#if activeTab === "password"}
      {@render passwordTabContent()}
    {:else if activeTab === "magic"}
      {@render magicTabContent()}
    {:else if activeTab === "social" && socialTabContent}
      {@render socialTabContent()}
    {:else if activeTab === "webauthn" && webauthnTabContent}
      {@render webauthnTabContent()}
    {/if}
  </div>
</div>
