// examples/demos/vue-demo/src/components/forms/TabForm.vue
<template>
  <div>
    <div class="tabs-container">
      <button
        class="tab-button"
        :class="{ 'tab-active': activeTab === 'password' }"
        @click="activeTab = 'password'"
      >
        Email + Password
      </button>
      <button
        class="tab-button"
        :class="{ 'tab-active': activeTab === 'magic' }"
        @click="activeTab = 'magic'"
      >
        Magic Link
      </button>
      <button
        v-if="$slots['social']"
        class="tab-button"
        :class="{ 'tab-active': activeTab === 'social' }"
        @click="activeTab = 'social'"
      >
        Social
      </button>
      <button
        v-if="$slots['webauthn']"
        class="tab-button"
        :class="{ 'tab-active': activeTab === 'webauthn' }"
        @click="activeTab = 'webauthn'"
      >
        Security Key
      </button>
    </div>

    <div class="tab-content">
      <div v-if="activeTab === 'password'">
        <slot name="password"></slot>
      </div>
      <div v-else-if="activeTab === 'magic'">
        <slot name="magic"></slot>
      </div>
      <div v-else-if="activeTab === 'social'">
        <slot name="social"></slot>
      </div>
      <div v-else-if="activeTab === 'webauthn'">
        <slot name="webauthn"></slot>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

type TabType = "password" | "magic" | "social" | "webauthn";

const activeTab = ref<TabType>("password");
</script>

// examples/demos/sveltekit-demo/src/lib/components/TabForm.svelte
<script lang="ts">
import type { Snippet } from "svelte";

interface Props {
  passwordTabContent: Snippet;
  magicTabContent: Snippet;
  socialTabContent?: Snippet;
  webauthnTabContent?: Snippet;
}

let {
  passwordTabContent,
  magicTabContent,
  socialTabContent,
  webauthnTabContent,
}: Props = $props();

let activeTab: "password" | "magic" | "social" | "webauthn" =
  $state("password");
</script>

<div>
  <div class="tabs-container">
    <button
      class="tab-button {activeTab === 'password' ? 'tab-active' : ''}"
      onclick={() => (activeTab = "password")}
    >
      Email + Password
    </button>
    <button
      class="tab-button {activeTab === 'magic' ? 'tab-active' : ''}"
      onclick={() => (activeTab = "magic")}
    >
      Magic Link
    </button>
    {#if socialTabContent}
      <button
        class="tab-button {activeTab === 'social' ? 'tab-active' : ''}"
        onclick={() => (activeTab = "social")}
      >
        Social
      </button>
    {/if}
    {#if webauthnTabContent}
      <button
        class="tab-button {activeTab === 'webauthn' ? 'tab-active' : ''}"
        onclick={() => (activeTab = "webauthn")}
      >
        Security Key
      </button>
    {/if}
  </div>

  <div class="tab-content">
    {#if activeTab === "password"}
      {@render passwordTabContent()}
    {:else if activeTab === "magic"}
      {@render magicTabContent()}
    {:else if activeTab === "social" && socialTabContent}
      {@render socialTabContent()}
    {:else if activeTab === "webauthn" && webauthnTabContent}
      {@render webauthnTabContent()}
    {/if}
  </div>
</div>
