// examples/demos/vue-demo/src/components/Navigation.vue
<template>
  <nav class="navbar">
    <div class="navbar-container">
      <router-link to="/" class="navbar-brand"> Nhost Vue Demo </router-link>

      <div class="navbar-links">
        <template v-if="isAuthenticated">
          <router-link
            to="/todos"
            class="nav-link"
            :class="{ active: $route.path === '/todos' }"
          >
            Todos
          </router-link>
          <router-link
            to="/profile"
            class="nav-link"
            :class="{ active: $route.path === '/profile' }"
          >
            Profile
          </router-link>
          <router-link
            to="/upload"
            class="nav-link"
            :class="{ active: $route.path === '/upload' }"
          >
            Upload
          </router-link>
          <button @click="handleSignOut" class="nav-link" :disabled="isLoading">
            {{ isLoading ? "Signing Out..." : "Sign Out" }}
          </button>
        </template>

        <template v-else>
          <router-link
            to="/signin"
            class="nav-link"
            :class="{ active: $route.path === '/signin' }"
          >
            Sign In
          </router-link>
          <router-link
            to="/signup"
            class="nav-link"
            :class="{ active: $route.path === '/signup' }"
          >
            Sign Up
          </router-link>
        </template>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useAuth } from "../lib/nhost/auth";

const { nhost, isAuthenticated, session } = useAuth();
const router = useRouter();
const isLoading = ref(false);

const handleSignOut = async () => {
  isLoading.value = true;

  try {
    if (session.value) {
      await nhost.auth.signOut({
        refreshToken: session.value.refreshToken,
      });
    }
    router.push("/");
  } catch (error) {
    console.error("Error signing out:", error);
  } finally {
    isLoading.value = false;
  }
};
</script>

<style scoped>
button.nav-link {
  background: none;
  border: none;
  cursor: pointer;
}

button.nav-link:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
</style>

// examples/tutorials/nhost-react-tutorial2/src/components/Navigation.tsx
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../lib/nhost/AuthProvider";

export default function Navigation() {
  const { isAuthenticated, session, nhost } = useAuth();
  const navigate = useNavigate();

  const handleSignOut = async () => {
    try {
      if (session) {
        await nhost.auth.signOut({
          refreshToken: session.refreshToken,
        });
      }
      navigate("/");
    } catch (err: any) {
      console.error("Error signing out:", err);
    }
  };

  return (
    <nav className="navigation">
      <div className="nav-container">
        <Link to="/" className="nav-logo">
          Nhost React Demo
        </Link>

        <div className="nav-links">
          <Link to="/" className="nav-link">
            Home
          </Link>

          {isAuthenticated ? (
            <>
              <Link to="/todos" className="nav-link">
                Todos
              </Link>
              <Link to="/profile" className="nav-link">
                Profile
              </Link>
              <button
                onClick={handleSignOut}
                className="nav-link nav-button"
              >
                Sign Out
              </button>
            </>
          ) : (
            <>
              <Link to="/signin" className="nav-link">
                Sign In
              </Link>
              <Link to="/signup" className="nav-link">
                Sign Up
              </Link>
            </>
          )}
        </div>
      </div>
    </nav>
  );
}
