// examples/quickstarts/nextjs-server-components/src/app/protected/page.tsx
'use server'

import { gql } from '@apollo/client'
import { getNhost } from '@utils/nhost'
import Head from 'next/head'

interface File {
  id: string
  name: string
}

export default async function Protected() {
  const nhost = await getNhost()
  const user = nhost.auth.getUser()

  const {
    data: { files }
  } = await nhost.graphql.request(gql`
    {
      files {
        id
        name
      }
    }
  `)

  return (
    <>
      <Head>
        <title>Protected Page</title>
      </Head>

      <h1 className="text-2xl font-semibold text-center">
        Hi! You are registered with email: {user?.email}.
      </h1>

      <p>Showing {files.length} files</p>

      <ul>
        {files.map((file: File) => (
          <li key={file.id}>{file.name}</li>
        ))}
      </ul>
    </>
  )
}

// examples/sveltekit/src/routes/protected/+page.svelte
<script>
	export let data;
	let { session, nhost } = data;
	import { gql } from 'graphql-tag';

	const getFiles = async () => {
		const response = await nhost.graphql.request(gql`
			{
				files {
					id
					name
				}
			}
		`);

		return response.data.files;
	};
</script>

<svelte:head>
	<title>Protected Page</title>
	<meta name="description" content="About this app" />
</svelte:head>

<h1 class="text-2xl font-semibold text-center">
	Hi! You are registered with email: {session?.user.email}.
</h1>

<h2>Files</h2>
{#await getFiles()}
	<p>Loading...</p>
{:then files}
	<p>Showing {files.length} files</p>

	<ul>
		{#each files as file}
			<li>
				{file.name}
			</li>
		{/each}
	</ul>
{:catch error}
	<p>{error.message}</p>
{/await}
