// examples/tutorials/nhost-vue-tutorial/src/components/Navigation.vue
<template>
  <nav class="navigation">
    <div class="nav-container">
      <RouterLink to="/" class="nav-logo">
        Nhost Vue Demo
      </RouterLink>

      <div class="nav-links">
        <RouterLink to="/" class="nav-link">
          Home
        </RouterLink>

        <template v-if="isAuthenticated">
          <RouterLink to="/profile" class="nav-link">
            Profile
          </RouterLink>
        </template>
        <template v-else>
          Placeholder for signin/signup links
        </template>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { RouterLink } from "vue-router";
import { useAuth } from "../lib/nhost/auth";

const { isAuthenticated } = useAuth();
</script>

// examples/demos/nextjs-ssr-demo/src/app/components/Navigation.tsx
import { createNhostClient } from '../lib/nhost/server';
import ActiveLink from './ActiveLink';
import SignOutButton from './SignOutButton';

export default async function Navigation() {
  const nhost = await createNhostClient();
  const session = nhost.getUserSession();

  return (
    <nav className="navbar">
      <div className="navbar-container">
        <div className="flex items-center">
          <span className="navbar-brand">Nhost Demo</span>
          <div className="navbar-links">
            {session ? (
              <>
                <ActiveLink href="/profile" className="nav-link">
                  Profile
                </ActiveLink>
                <ActiveLink href="/upload" className="nav-link">
                  Upload
                </ActiveLink>
              </>
            ) : (
              <>
                <ActiveLink href="/signin" className="nav-link">
                  Sign In
                </ActiveLink>
                <ActiveLink href="/signup" className="nav-link">
                  Sign Up
                </ActiveLink>
              </>
            )}
          </div>
        </div>

        {session && <SignOutButton />}
      </div>
    </nav>
  );
}
