// examples/demos/vue-demo/src/components/profile/MFASettings.vue
<template>
  <div class="glass-card p-8 mb-6">
    <h3 class="text-xl mb-4">Multi-Factor Authentication</h3>

    <div v-if="error" class="alert alert-error mb-4">{{ error }}</div>

    <div v-if="success" class="alert alert-success mb-4">{{ success }}</div>

    <div v-if="isSettingUpMfa" class="space-y-5">
      <p>
        Scan this QR code with your authenticator app (e.g., Google
        Authenticator, Authy):
      </p>

      <div v-if="qrCodeUrl" class="flex justify-center my-4">
        <div class="p-2 bg-white rounded-md">
          <img :src="qrCodeUrl" alt="TOTP QR Code" width="200" height="200" />
        </div>
      </div>

      <p>Or manually enter this secret key:</p>
      <div class="p-2 bg-gray-100 rounded text-center text-black">
        {{ totpSecret }}
      </div>

      <div>
        <label for="verification-code">Verification Code</label>
        <input
          id="verification-code"
          type="text"
          v-model="verificationCode"
          placeholder="Enter 6-digit code"
          maxlength="6"
          required
        />
      </div>

      <div class="flex space-x-3">
        <button
          @click="handleVerifyTotp"
          :disabled="isLoading || !verificationCode"
          class="btn btn-primary"
        >
          {{ isLoading ? "Verifying..." : "Verify and Enable" }}
        </button>

        <button
          @click="handleCancelMfaSetup"
          :disabled="isLoading"
          class="btn btn-secondary"
        >
          Cancel
        </button>
      </div>
    </div>

    <div v-else-if="isDisablingMfa" class="space-y-5">
      <p>
        To disable Multi-Factor Authentication, please enter the current
        verification code from your authenticator app.
      </p>

      <div>
        <label for="disable-verification-code">
          Current Verification Code
        </label>
        <input
          id="disable-verification-code"
          type="text"
          v-model="disableVerificationCode"
          placeholder="Enter 6-digit code"
          maxlength="6"
          required
        />
      </div>

      <div class="flex space-x-3">
        <button
          @click="handleDisableMfa"
          :disabled="isLoading || !disableVerificationCode"
          class="btn btn-primary"
        >
          {{ isLoading ? "Disabling..." : "Confirm Disable" }}
        </button>

        <button
          @click="handleCancelMfaDisable"
          :disabled="isLoading"
          class="btn btn-secondary"
        >
          Cancel
        </button>
      </div>
    </div>

    <div v-else class="space-y-5">
      <p>
        Multi-Factor Authentication adds an extra layer of security to your
        account by requiring a verification code from your authenticator app
        when signing in.
      </p>

      <div class="flex items-center">
        <span class="mr-3">Status:</span>
        <span
          class="font-semibold"
          :class="isMfaEnabled ? 'text-green-500' : 'text-yellow-500'"
        >
          {{ isMfaEnabled ? "Enabled" : "Disabled" }}
        </span>
      </div>

      <button
        v-if="isMfaEnabled"
        @click="handleShowDisableMfa"
        :disabled="isLoading"
        class="btn btn-secondary"
      >
        {{ isLoading ? "Processing..." : "Disable MFA" }}
      </button>
      <button
        v-else
        @click="handleEnableMfa"
        :disabled="isLoading"
        class="btn btn-primary"
      >
        {{ isLoading ? "Loading..." : "Enable MFA" }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { type ErrorResponse } from '@nhost/nhost-js/auth';
import { type FetchError } from '@nhost/nhost-js/fetch';
import { ref, watch } from 'vue';
import { useAuth } from '../../lib/nhost/auth';

interface Props {
  initialMfaEnabled: boolean;
}

const props = defineProps<Props>();

const { nhost } = useAuth();

const isMfaEnabled = ref<boolean>(props.initialMfaEnabled);
const isLoading = ref<boolean>(false);
const error = ref<string | null>(null);
const success = ref<string | null>(null);

// MFA setup states
const isSettingUpMfa = ref<boolean>(false);
const totpSecret = ref<string>('');
const qrCodeUrl = ref<string>('');
const verificationCode = ref<string>('');

// Disabling MFA states
const isDisablingMfa = ref<boolean>(false);
const disableVerificationCode = ref<string>('');

// Update internal state when prop changes
watch(
  () => props.initialMfaEnabled,
  (newValue) => {
    if (newValue !== isMfaEnabled.value) {
      isMfaEnabled.value = newValue;
    }
  },
);

// Begin MFA setup process
const handleEnableMfa = async (): Promise<void> => {
  isLoading.value = true;
  error.value = null;
  success.value = null;

  try {
    // Generate TOTP secret
    const response = await nhost.auth.changeUserMfa();
    totpSecret.value = response.body.totpSecret;
    qrCodeUrl.value = response.body.imageUrl;
    isSettingUpMfa.value = true;
  } catch (err) {
    const errorObj = err as FetchError<ErrorResponse>;
    error.value = `An error occurred while enabling MFA: ${errorObj.message}`;
  } finally {
    isLoading.value = false;
  }
};

// Verify TOTP and enable MFA
const handleVerifyTotp = async (): Promise<void> => {
  if (!verificationCode.value) {
    error.value = 'Please enter the verification code';
    return;
  }

  isLoading.value = true;
  error.value = null;
  success.value = null;

  try {
    // Verify and activate MFA
    await nhost.auth.verifyChangeUserMfa({
      activeMfaType: 'totp',
      code: verificationCode.value,
    });

    isMfaEnabled.value = true;
    isSettingUpMfa.value = false;
    success.value = 'MFA has been successfully enabled.';
  } catch (err) {
    const errorObj = err as FetchError<ErrorResponse>;
    error.value = `An error occurred while verifying the code: ${errorObj.message}`;
  } finally {
    isLoading.value = false;
  }
};

// Show disable MFA confirmation
const handleShowDisableMfa = (): void => {
  isDisablingMfa.value = true;
  error.value = null;
  success.value = null;
};

// Disable MFA
const handleDisableMfa = async (): Promise<void> => {
  if (!disableVerificationCode.value) {
    error.value = 'Please enter your verification code to confirm';
    return;
  }

  isLoading.value = true;
  error.value = null;
  success.value = null;

  try {
    // Disable MFA by setting activeMfaType to empty string
    await nhost.auth.verifyChangeUserMfa({
      activeMfaType: '',
      code: disableVerificationCode.value,
    });

    isMfaEnabled.value = false;
    isDisablingMfa.value = false;
    disableVerificationCode.value = '';
    success.value = 'MFA has been successfully disabled.';
  } catch (err) {
    const errorObj = err as FetchError<ErrorResponse>;
    error.value = `An error occurred while disabling MFA: ${errorObj.message}`;
  } finally {
    isLoading.value = false;
  }
};

// Cancel MFA setup
const handleCancelMfaSetup = (): void => {
  isSettingUpMfa.value = false;
  totpSecret.value = '';
  qrCodeUrl.value = '';
  verificationCode.value = '';
};

// Cancel MFA disable
const handleCancelMfaDisable = (): void => {
  isDisablingMfa.value = false;
  disableVerificationCode.value = '';
  error.value = null;
};
</script>

// examples/demos/nextjs-ssr-demo/src/app/profile/mfa-settings.tsx
"use client";

import { useState } from "react";
import { useAuth } from "../lib/nhost/AuthProvider";
import Image from "next/image";

interface MFASettingsProps {
  initialMfaEnabled: boolean;
}

export default function MFASettings({ initialMfaEnabled }: MFASettingsProps) {
  const { nhost } = useAuth();
  const [isMfaEnabled, setIsMfaEnabled] = useState(initialMfaEnabled);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  // MFA setup states
  const [isSettingUpMfa, setIsSettingUpMfa] = useState(false);
  const [totpSecret, setTotpSecret] = useState("");
  const [qrCodeUrl, setQrCodeUrl] = useState("");
  const [verificationCode, setVerificationCode] = useState("");

  // Disabling MFA states
  const [isDisablingMfa, setIsDisablingMfa] = useState(false);
  const [disableVerificationCode, setDisableVerificationCode] = useState("");

  // Begin MFA setup process
  const handleEnableMfa = async () => {
    setIsLoading(true);
    setError(null);
    setSuccess(null);

    try {
      // Generate TOTP secret
      const response = await nhost.auth.changeUserMfa();

      if (response.body) {
        setTotpSecret(response.body.totpSecret);
        setQrCodeUrl(response.body.imageUrl);
        setIsSettingUpMfa(true);
      }
    } catch (err) {
      console.error("Error generating TOTP secret:", err);
      setError("Failed to generate TOTP secret. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  // Verify TOTP and enable MFA
  const handleVerifyTotp = async () => {
    if (!verificationCode) {
      setError("Please enter the verification code");
      return;
    }

    setIsLoading(true);
    setError(null);
    setSuccess(null);

    try {
      // Verify and activate MFA
      const response = await nhost.auth.verifyChangeUserMfa({
        activeMfaType: "totp",
        code: verificationCode,
      });

      if (response.body) {
        setIsMfaEnabled(true);
        setIsSettingUpMfa(false);
        setSuccess("MFA has been successfully enabled.");
      }
    } catch (err) {
      console.error("Error verifying TOTP:", err);
      setError(
        "Failed to verify code. Please make sure you entered the correct code from your authenticator app.",
      );
    } finally {
      setIsLoading(false);
    }
  };

  // Show disable MFA confirmation
  const handleShowDisableMfa = () => {
    setIsDisablingMfa(true);
    setError(null);
    setSuccess(null);
  };

  // Disable MFA
  const handleDisableMfa = async () => {
    if (!disableVerificationCode) {
      setError("Please enter your verification code to confirm");
      return;
    }

    setIsLoading(true);
    setError(null);
    setSuccess(null);

    try {
      // Disable MFA by setting activeMfaType to empty string
      // We need to provide the current TOTP code to verify identity
      const response = await nhost.auth.verifyChangeUserMfa({
        activeMfaType: "",
        code: disableVerificationCode,
      });

      if (response.body) {
        setIsMfaEnabled(false);
        setIsDisablingMfa(false);
        setDisableVerificationCode("");
        setSuccess("MFA has been successfully disabled.");
      }
    } catch (err) {
      console.error("Error disabling MFA:", err);
      setError(
        "Failed to disable MFA. Please make sure you entered the correct verification code from your authenticator app.",
      );
    } finally {
      setIsLoading(false);
    }
  };

  // Cancel MFA setup
  const handleCancelMfaSetup = () => {
    setIsSettingUpMfa(false);
    setTotpSecret("");
    setQrCodeUrl("");
    setVerificationCode("");
  };

  // Cancel MFA disable
  const handleCancelMfaDisable = () => {
    setIsDisablingMfa(false);
    setDisableVerificationCode("");
    setError(null);
  };

  return (
    <div className="glass-card p-8">
      <h3 className="text-xl mb-4">Multi-Factor Authentication</h3>

      {error && <div className="alert alert-error mb-4">{error}</div>}

      {success && <div className="alert alert-success mb-4">{success}</div>}

      {isSettingUpMfa ? (
        <div className="space-y-5">
          <p>
            Scan this QR code with your authenticator app (e.g., Google
            Authenticator, Authy):
          </p>

          {qrCodeUrl && (
            <div className="flex justify-center my-4">
              <div className="p-2 bg-white rounded-md">
                <Image
                  src={qrCodeUrl}
                  alt="TOTP QR Code"
                  width={200}
                  height={200}
                />
              </div>
            </div>
          )}

          <p>Or manually enter this secret key:</p>
          <div className="p-2 bg-gray-100 rounded font-mono text-center">
            {totpSecret}
          </div>

          <div>
            <label htmlFor="verification-code">Verification Code</label>
            <input
              id="verification-code"
              type="text"
              value={verificationCode}
              onChange={(e) => setVerificationCode(e.target.value)}
              placeholder="Enter 6-digit code"
              maxLength={6}
              required
            />
          </div>

          <div className="flex space-x-3">
            <button
              onClick={handleVerifyTotp}
              disabled={isLoading || !verificationCode}
              className="btn btn-primary"
            >
              {isLoading ? "Verifying..." : "Verify and Enable"}
            </button>

            <button
              onClick={handleCancelMfaSetup}
              disabled={isLoading}
              className="btn btn-secondary"
            >
              Cancel
            </button>
          </div>
        </div>
      ) : isDisablingMfa ? (
        <div className="space-y-5">
          <p>
            To disable Multi-Factor Authentication, please enter the current
            verification code from your authenticator app.
          </p>

          <div>
            <label htmlFor="disable-verification-code">
              Current Verification Code
            </label>
            <input
              id="disable-verification-code"
              type="text"
              value={disableVerificationCode}
              onChange={(e) => setDisableVerificationCode(e.target.value)}
              placeholder="Enter 6-digit code"
              maxLength={6}
              required
            />
          </div>

          <div className="flex space-x-3">
            <button
              onClick={handleDisableMfa}
              disabled={isLoading || !disableVerificationCode}
              className="btn btn-primary"
            >
              {isLoading ? "Disabling..." : "Confirm Disable"}
            </button>

            <button
              onClick={handleCancelMfaDisable}
              disabled={isLoading}
              className="btn btn-secondary"
            >
              Cancel
            </button>
          </div>
        </div>
      ) : (
        <div className="space-y-5">
          <p>
            Multi-Factor Authentication adds an extra layer of security to your
            account by requiring a verification code from your authenticator app
            when signing in.
          </p>

          <div className="flex items-center">
            <span className="mr-3">Status:</span>
            <span
              className={`font-semibold ${isMfaEnabled ? "text-green-500" : "text-yellow-500"}`}
            >
              {isMfaEnabled ? "Enabled" : "Disabled"}
            </span>
          </div>

          {isMfaEnabled ? (
            <button
              onClick={handleShowDisableMfa}
              disabled={isLoading}
              className="btn btn-secondary"
            >
              {isLoading ? "Processing..." : "Disable MFA"}
            </button>
          ) : (
            <button
              onClick={handleEnableMfa}
              disabled={isLoading}
              className="btn btn-primary"
            >
              {isLoading ? "Loading..." : "Enable MFA"}
            </button>
          )}
        </div>
      )}
    </div>
  );
}
