// templates/nextjs/frontend/src/app/auth/magic-link/MagicLinkForm.tsx
'use client';

import { type FormEvent, useId, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { sendMagicLink } from './actions';

export default function MagicLinkForm({
  next,
  mailboxURL,
}: {
  next: string;
  mailboxURL: string | null;
}) {
  const emailId = useId();

  const [email, setEmail] = useState('');
  const [sent, setSent] = useState(false);
  const [error, setError] = useState<string | undefined>();
  const [isSending, setIsSending] = useState(false);

  const handleSubmit = async (event: FormEvent): Promise<void> => {
    event.preventDefault();
    setError(undefined);
    setIsSending(true);
    try {
      const result = await sendMagicLink(email, next);
      if (result?.error) {
        setError(result.error);
        return;
      }

      setSent(true);
    } catch (err) {
      console.error('Error sending the magic link:', err);
      setError('The request did not reach the server. Try again.');
    } finally {
      setIsSending(false);
    }
  };

  const useDifferentAddress = (): void => {
    setSent(false);
    setEmail('');
    setError(undefined);
  };

  if (sent) {
    return (
      <div className="flex flex-col gap-4">
        <p className="text-sm">
          A sign-in link is on its way to {email}. Opening it signs you in on
          this device.
        </p>
        {mailboxURL ? (
          <p className="text-muted-foreground text-sm">
            Running locally? The email is in the{' '}
            <a
              href={mailboxURL}
              target="_blank"
              rel="noreferrer"
              className="underline underline-offset-4"
            >
              local mailbox
            </a>
            .
          </p>
        ) : null}
        <Button
          type="button"
          variant="ghost"
          size="sm"
          onClick={useDifferentAddress}
          className="self-start"
        >
          Use a different address
        </Button>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-4">
      <div className="flex flex-col gap-2">
        <Label htmlFor={emailId}>Email</Label>
        <Input
          id={emailId}
          name="email"
          type="email"
          autoComplete="email"
          placeholder="you@example.com"
          value={email}
          onChange={(event) => setEmail(event.target.value)}
          disabled={isSending}
          required
        />
      </div>

      {error ? (
        <p role="alert" className="text-destructive text-sm">
          {error}
        </p>
      ) : null}

      <Button type="submit" disabled={isSending || !email}>
        {isSending ? 'Sending…' : 'Send me a link'}
      </Button>
    </form>
  );
}

// templates/svelte/frontend/src/routes/auth/magic-link/MagicLinkForm.svelte
<script lang="ts">
import { Button } from '$lib/components/ui/button';
import { Input } from '$lib/components/ui/input';
import { Label } from '$lib/components/ui/label';
import { useAuth } from '$lib/nhost/auth.svelte';
import { sendMagicLink } from './actions';

let { next, mailboxUrl }: { next: string; mailboxUrl: string | null } =
  $props();

const auth = useAuth();
const uid = $props.id();
const emailId = `${uid}-email`;

let email = $state('');
let sent = $state(false);
let error = $state<string | undefined>();
let isSending = $state(false);

async function handleSubmit(event: SubmitEvent): Promise<void> {
  event.preventDefault();
  error = undefined;
  isSending = true;
  try {
    const result = await sendMagicLink(auth.nhost, email, next);
    if (result?.error) {
      error = result.error;
      return;
    }

    sent = true;
  } catch (err) {
    console.error('Error sending the magic link:', err);
    error = 'The request did not reach the server. Try again.';
  } finally {
    isSending = false;
  }
}

function useDifferentAddress(): void {
  sent = false;
  email = '';
  error = undefined;
}
</script>

{#if sent}
  <div class="flex flex-col gap-4">
    <p class="text-sm">
      A sign-in link is on its way to {email}. Opening it signs you in on this
      device.
    </p>
    {#if mailboxUrl}
      <p class="text-muted-foreground text-sm">
        Running locally? The email is in the
        <a
          href={mailboxUrl}
          target="_blank"
          rel="noreferrer"
          class="underline underline-offset-4">local mailbox</a
        >.
      </p>
    {/if}
    <Button
      type="button"
      variant="ghost"
      size="sm"
      class="self-start"
      onclick={useDifferentAddress}
    >
      Use a different address
    </Button>
  </div>
{:else}
  <form class="flex flex-col gap-4" onsubmit={handleSubmit}>
    <div class="flex flex-col gap-2">
      <Label for={emailId}>Email</Label>
      <Input
        id={emailId}
        type="email"
        autocomplete="email"
        placeholder="you@example.com"
        required
        bind:value={email}
        disabled={isSending}
      />
    </div>

    {#if error}
      <p role="alert" class="text-destructive text-sm">{error}</p>
    {/if}

    <Button type="submit" disabled={isSending || !email}>
      {isSending ? 'Sending…' : 'Send me a link'}
    </Button>
  </form>
{/if}
