// examples/vue-apollo/src/pages/sign-in/Main.vue
<template>
  <Links />
  <v-divider class="my-4" />
  <v-btn class="my-1" block variant="outlined" prepend-icon="mdi-lock" color="primary" to="/signin/passwordless"
    >Continue with passwordless email</v-btn
  >
  <v-btn class="my-1" block variant="text" color="primary" to="/signin/email-password"
    >Continue with email + password</v-btn
  >
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import Links from '../../components/OAuthLinks.vue'
export default defineComponent({
  components: {
    Links
  }
})
</script>

// examples/nextjs/src/pages/sign-in/index.tsx
import { NextPage } from 'next'
import { FaLock } from 'react-icons/fa'

import { Divider } from '@mantine/core'

import AuthLink from '../../components/AuthLink'
import OAuthLinks from '../../components/OauthLinks'
import SignInLayout from '../../layouts/SignInLayout'

export const SignInPage: NextPage = () => {
  return (
    <SignInLayout title="Sign In">
      <OAuthLinks />
      <Divider my="sm" />
      <AuthLink icon={<FaLock />} variant="outline" link="/sign-in/passwordless">
        Continue with passwordless email
      </AuthLink>
      <AuthLink variant="subtle" link="/sign-in/email-password">
        Continue with email + password
      </AuthLink>
    </SignInLayout>
  )
}

export default SignInPage
