// templates/svelte/frontend/src/routes/auth/magic-link/MagicLinkForm.svelte
<script lang="ts">
import { Button } from '$lib/components/ui/button';
import { Input } from '$lib/components/ui/input';
import { Label } from '$lib/components/ui/label';
import { useAuth } from '$lib/nhost/auth.svelte';
import { sendMagicLink } from './actions';

let { next, mailboxUrl }: { next: string; mailboxUrl: string | null } =
  $props();

const auth = useAuth();
const uid = $props.id();
const emailId = `${uid}-email`;

let email = $state('');
let sent = $state(false);
let error = $state<string | undefined>();
let isSending = $state(false);

async function handleSubmit(event: SubmitEvent): Promise<void> {
  event.preventDefault();
  error = undefined;
  isSending = true;
  try {
    const result = await sendMagicLink(auth.nhost, email, next);
    if (result?.error) {
      error = result.error;
      return;
    }

    sent = true;
  } catch (err) {
    console.error('Error sending the magic link:', err);
    error = 'The request did not reach the server. Try again.';
  } finally {
    isSending = false;
  }
}

function useDifferentAddress(): void {
  sent = false;
  email = '';
  error = undefined;
}
</script>

{#if sent}
  <div class="flex flex-col gap-4">
    <p class="text-sm">
      A sign-in link is on its way to {email}. Opening it signs you in on this
      device.
    </p>
    {#if mailboxUrl}
      <p class="text-muted-foreground text-sm">
        Running locally? The email is in the
        <a
          href={mailboxUrl}
          target="_blank"
          rel="noreferrer"
          class="underline underline-offset-4">local mailbox</a
        >.
      </p>
    {/if}
    <Button
      type="button"
      variant="ghost"
      size="sm"
      class="self-start"
      onclick={useDifferentAddress}
    >
      Use a different address
    </Button>
  </div>
{:else}
  <form class="flex flex-col gap-4" onsubmit={handleSubmit}>
    <div class="flex flex-col gap-2">
      <Label for={emailId}>Email</Label>
      <Input
        id={emailId}
        type="email"
        autocomplete="email"
        placeholder="you@example.com"
        required
        bind:value={email}
        disabled={isSending}
      />
    </div>

    {#if error}
      <p role="alert" class="text-destructive text-sm">{error}</p>
    {/if}

    <Button type="submit" disabled={isSending || !email}>
      {isSending ? 'Sending…' : 'Send me a link'}
    </Button>
  </form>
{/if}

// templates/vue/frontend/src/auth/magic-link/MagicLinkForm.vue
<script setup lang="ts">
import { ref, useId } from 'vue';
import { sendMagicLink } from '@/auth/magic-link/actions';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useAuth } from '@/lib/nhost/auth';

const props = defineProps<{ next: string; mailboxUrl: string | null }>();

const { nhost } = useAuth();
const emailId = useId();

const email = ref('');
const sent = ref(false);
const error = ref<string | undefined>();
const isSending = ref(false);

const handleSubmit = async (): Promise<void> => {
  error.value = undefined;
  isSending.value = true;
  try {
    const result = await sendMagicLink(nhost, email.value, props.next);
    if (result?.error) {
      error.value = result.error;
      return;
    }

    sent.value = true;
  } catch (err) {
    console.error('Error sending the magic link:', err);
    error.value = 'The request did not reach the server. Try again.';
  } finally {
    isSending.value = false;
  }
};

const useDifferentAddress = (): void => {
  sent.value = false;
  email.value = '';
  error.value = undefined;
};
</script>

<template>
  <div v-if="sent" class="flex flex-col gap-4">
    <p class="text-sm">
      A sign-in link is on its way to {{ email }}. Opening it signs you in on
      this device.
    </p>
    <p v-if="mailboxUrl" class="text-muted-foreground text-sm">
      Running locally? The email is in the
      <a
        :href="mailboxUrl"
        target="_blank"
        rel="noreferrer"
        class="underline underline-offset-4"
      >local mailbox</a>.
    </p>
    <Button
      type="button"
      variant="ghost"
      size="sm"
      class="self-start"
      @click="useDifferentAddress"
    >
      Use a different address
    </Button>
  </div>

  <form v-else class="flex flex-col gap-4" @submit.prevent="handleSubmit">
    <div class="flex flex-col gap-2">
      <Label :for="emailId">Email</Label>
      <Input
        :id="emailId"
        v-model="email"
        type="email"
        autocomplete="email"
        placeholder="you@example.com"
        required
        :disabled="isSending"
      />
    </div>

    <p v-if="error" role="alert" class="text-destructive text-sm">
      {{ error }}
    </p>

    <Button type="submit" :disabled="isSending || !email">
      {{ isSending ? 'Sending…' : 'Send me a link' }}
    </Button>
  </form>
</template>
