// examples/demos/vue-demo/src/views/Todos.vue
<template>
  <div v-if="!session" class="auth-message">
    <p>Please sign in to view your todos.</p>
  </div>

  <div v-else class="container">
    <header class="page-header">
      <h1 class="page-title">
        My Todos
        <button
          v-if="!showAddForm"
          type="button"
          @click="showAddForm = true"
          class="add-todo-btn"
          title="Add a new todo"
        >
          +
        </button>
      </h1>
    </header>

    <div v-if="error" class="error-message">
      <strong>Error:</strong> {{ error }}
    </div>

    <div v-if="showAddForm" class="todo-form-card">
      <form @submit.prevent="addTodo" class="todo-form">
        <h2 class="form-title">Add New Todo</h2>
        <div class="form-fields">
          <div class="field-group">
            <label :for="titleId">Title *</label>
            <input
              :id="titleId"
              type="text"
              v-model="newTodoTitle"
              placeholder="What needs to be done?"
              required
            />
          </div>
          <div class="field-group">
            <label :for="detailsId">Details</label>
            <textarea
              :id="detailsId"
              v-model="newTodoDetails"
              placeholder="Add some details (optional)..."
              :rows="3"
            />
          </div>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">
              Add Todo
            </button>
            <button
              type="button"
              @click="cancelAddForm"
              class="btn btn-secondary"
            >
              Cancel
            </button>
          </div>
        </div>
      </form>
    </div>

    <div v-if="!showAddForm">
      <div v-if="loading" class="loading-container">
        <div class="loading-content">
          <div class="spinner"></div>
          <span class="loading-text">Loading todos...</span>
        </div>
      </div>

      <div v-else class="todos-list">
        <div v-if="todos.length === 0" class="empty-state">
          <svg
            class="empty-icon"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            aria-hidden="true"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              :stroke-width="1.5"
              d="M9 5H7a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"
            />
          </svg>
          <h3 class="empty-title">No todos yet</h3>
          <p class="empty-description">
            Create your first todo to get started!
          </p>
        </div>

        <div
          v-else
          v-for="todo in todos"
          :key="todo.id"
          :class="['todo-card', { completed: todo.completed }]"
        >
          <div v-if="editingTodo?.id === todo.id" class="todo-edit">
            <div class="edit-fields">
              <div class="field-group">
                <label :for="`${titleId}-edit`">Title</label>
                <input
                  :id="`${titleId}-edit`"
                  type="text"
                  v-model="editingTodo.title"
                />
              </div>
              <div class="field-group">
                <label :for="`${detailsId}-edit`">Details</label>
                <textarea
                  :id="`${detailsId}-edit`"
                  v-model="editingTodo.details"
                  :rows="3"
                />
              </div>
              <div class="edit-actions">
                <button
                  type="button"
                  @click="saveEdit"
                  class="btn btn-primary"
                >
                  ✓ Save Changes
                </button>
                <button
                  type="button"
                  @click="editingTodo = null"
                  class="btn btn-cancel"
                >
                  ✕ Cancel
                </button>
              </div>
            </div>
          </div>

          <div v-else class="todo-content">
            <div class="todo-header">
              <button
                type="button"
                :class="['todo-title-btn', { completed: todo.completed }]"
                @click="toggleTodoExpansion(todo.id)"
              >
                {{ todo.title }}
              </button>
              <div class="todo-actions">
                <button
                  type="button"
                  @click="toggleComplete(todo)"
                  class="action-btn action-btn-complete"
                  :title="todo.completed ? 'Mark as incomplete' : 'Mark as complete'"
                >
                  {{ todo.completed ? "↶" : "✓" }}
                </button>
                <button
                  type="button"
                  @click="editingTodo = todo"
                  class="action-btn action-btn-edit"
                  title="Edit todo"
                >
                  ✏️
                </button>
                <button
                  type="button"
                  @click="deleteTodo(todo.id)"
                  class="action-btn action-btn-delete"
                  title="Delete todo"
                >
                  🗑️
                </button>
              </div>
            </div>

            <div v-if="expandedTodos.has(todo.id)" class="todo-details">
              <div
                v-if="todo.details"
                :class="['todo-description', { completed: todo.completed }]"
              >
                <p>{{ todo.details }}</p>
              </div>

              <div class="todo-meta">
                <div class="meta-dates">
                  <span class="meta-item">
                    Created: {{ new Date(todo.created_at).toLocaleString() }}
                  </span>
                  <span class="meta-item">
                    Updated: {{ new Date(todo.updated_at).toLocaleString() }}
                  </span>
                </div>
                <div v-if="todo.completed" class="completion-badge">
                  <svg
                    class="completion-icon"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    aria-hidden="true"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      :stroke-width="2"
                      d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                  </svg>
                  <span>Completed</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref, useId } from 'vue';
import { useAuth } from '../lib/nhost/auth';

// The interfaces below define the structure of our data
// They are not strictly necessary but help with type safety

// Represents a single todo item
interface Todo {
  id: string;
  title: string;
  details: string | null;
  completed: boolean;
  created_at: string;
  updated_at: string;
  user_id: string;
}

// This matches the GraphQL response structure for fetching todos
// Can be used as a generic type on the request method
interface GetTodos {
  todos: Todo[];
}

// This matches the GraphQL response structure for inserting a todo
// Can be used as a generic type on the request method
interface InsertTodo {
  insert_todos_one: Todo | null;
}

// This matches the GraphQL response structure for updating a todo
// Can be used as a generic type on the request method
interface UpdateTodo {
  update_todos_by_pk: Todo | null;
}

const { nhost, session } = useAuth();

const todos = ref<Todo[]>([]);
const loading = ref(true);
const error = ref<string | null>(null);
const newTodoTitle = ref('');
const newTodoDetails = ref('');
const editingTodo = ref<Todo | null>(null);
const showAddForm = ref(false);
const expandedTodos = ref<Set<string>>(new Set());

const titleId = useId();
const detailsId = useId();

const fetchTodos = async () => {
  try {
    loading.value = true;
    // Make GraphQL request to fetch todos using Nhost client
    // The query automatically filters by user_id due to Hasura permissions
    const response = await nhost.graphql.request<GetTodos>({
      query: `
        query GetTodos {
          todos(order_by: { created_at: desc }) {
            id
            title
            details
            completed
            created_at
            updated_at
            user_id
          }
        }
      `,
    });

    // Check for GraphQL errors in the response body
    if (response.body.errors) {
      throw new Error(
        response.body.errors[0]?.message || 'Failed to fetch todos',
      );
    }

    // Extract todos from the GraphQL response data
    todos.value = response.body?.data?.todos || [];
    error.value = null;
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to fetch todos';
  } finally {
    loading.value = false;
  }
};

const addTodo = async () => {
  if (!newTodoTitle.value.trim()) return;

  try {
    // Execute GraphQL mutation to insert a new todo
    // user_id is automatically set by Hasura based on JWT token
    const response = await nhost.graphql.request<InsertTodo>({
      query: `
        mutation InsertTodo($title: String!, $details: String) {
          insert_todos_one(object: { title: $title, details: $details }) {
            id
            title
            details
            completed
            created_at
            updated_at
            user_id
          }
        }
      `,
      variables: {
        title: newTodoTitle.value.trim(),
        details: newTodoDetails.value.trim() || null,
      },
    });

    if (response.body.errors) {
      throw new Error(response.body.errors[0]?.message || 'Failed to add todo');
    }

    if (!response.body?.data?.insert_todos_one) {
      throw new Error('Failed to add todo');
    }
    todos.value = [response.body?.data?.insert_todos_one, ...todos.value];
    newTodoTitle.value = '';
    newTodoDetails.value = '';
    showAddForm.value = false;
    error.value = null;
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to add todo';
  }
};

const updateTodo = async (
  id: string,
  updates: Partial<Pick<Todo, 'title' | 'details' | 'completed'>>,
) => {
  try {
    // Execute GraphQL mutation to update an existing todo by primary key
    // Hasura permissions ensure users can only update their own todos
    const response = await nhost.graphql.request<UpdateTodo>({
      query: `
        mutation UpdateTodo($id: uuid!, $updates: todos_set_input!) {
          update_todos_by_pk(pk_columns: { id: $id }, _set: $updates) {
            id
            title
            details
            completed
            created_at
            updated_at
            user_id
          }
        }
      `,
      variables: {
        id,
        updates,
      },
    });

    if (response.body.errors) {
      throw new Error(
        response.body.errors[0]?.message || 'Failed to update todo',
      );
    }

    if (!response.body?.data?.update_todos_by_pk) {
      throw new Error('Failed to update todo');
    }

    const updatedTodo = response.body?.data?.update_todos_by_pk;
    if (updatedTodo) {
      todos.value = todos.value.map((todo) =>
        todo.id === id ? updatedTodo : todo,
      );
    }
    editingTodo.value = null;
    error.value = null;
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to update todo';
  }
};

const deleteTodo = async (id: string) => {
  if (!confirm('Are you sure you want to delete this todo?')) return;

  try {
    // Execute GraphQL mutation to delete a todo by primary key
    // Hasura permissions ensure users can only delete their own todos
    const response = await nhost.graphql.request({
      query: `
        mutation DeleteTodo($id: uuid!) {
          delete_todos_by_pk(id: $id) {
            id
          }
        }
      `,
      variables: {
        id,
      },
    });

    if (response.body.errors) {
      throw new Error(
        response.body.errors[0]?.message || 'Failed to delete todo',
      );
    }

    todos.value = todos.value.filter((todo) => todo.id !== id);
    error.value = null;
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to delete todo';
  }
};

const toggleComplete = async (todo: Todo) => {
  await updateTodo(todo.id, { completed: !todo.completed });
};

const saveEdit = async () => {
  if (!editingTodo.value) return;
  await updateTodo(editingTodo.value.id, {
    title: editingTodo.value.title,
    details: editingTodo.value.details,
  });
};

const toggleTodoExpansion = (todoId: string) => {
  const newExpanded = new Set(expandedTodos.value);
  if (newExpanded.has(todoId)) {
    newExpanded.delete(todoId);
  } else {
    newExpanded.add(todoId);
  }
  expandedTodos.value = newExpanded;
};

const cancelAddForm = () => {
  showAddForm.value = false;
  newTodoTitle.value = '';
  newTodoDetails.value = '';
};

// Fetch todos when user session is available
// The session contains the JWT token needed for GraphQL authentication
onMounted(() => {
  if (session.value) {
    fetchTodos();
  }
});
</script>

// examples/tutorials/nhost-reactnative-tutorial/app/todos.tsx
import { Stack, router } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  FlatList,
  ScrollView,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";
import ProtectedScreen from "./components/ProtectedScreen";
import { useAuth } from "./lib/nhost/AuthProvider";
import { commonStyles } from "./styles/commonStyles";

// The interfaces below define the structure of our data
// They are not strictly necessary but help with type safety

// Represents a single todo item
interface Todo {
  id: string;
  title: string;
  details: string | null;
  completed: boolean;
  created_at: string;
  updated_at: string;
  user_id: string;
}

// This matches the GraphQL response structure for fetching todos
// Can be used as a generic type on the request method
interface GetTodos {
  todos: Todo[];
}

// This matches the GraphQL response structure for inserting a todo
// Can be used as a generic type on the request method
interface InsertTodo {
  insert_todos_one: Todo | null;
}

// This matches the GraphQL response structure for updating a todo
// Can be used as a generic type on the request method
interface UpdateTodo {
  update_todos_by_pk: Todo | null;
}

export default function Todos() {
  const { nhost, session } = useAuth();
  const [todos, setTodos] = useState<Todo[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [newTodoTitle, setNewTodoTitle] = useState("");
  const [newTodoDetails, setNewTodoDetails] = useState("");
  const [editingTodo, setEditingTodo] = useState<Todo | null>(null);
  const [showAddForm, setShowAddForm] = useState(false);
  const [expandedTodos, setExpandedTodos] = useState<Set<string>>(new Set());
  const [addingTodo, setAddingTodo] = useState(false);
  const [updatingTodos, setUpdatingTodos] = useState<Set<string>>(new Set());


  // Redirect to sign in if not authenticated
  useEffect(() => {
    if (!session) {
      router.replace("/signin");
    }
  }, [session]);

  const fetchTodos = useCallback(async () => {
    try {
      setLoading(true);
      // Make GraphQL request to fetch todos using Nhost client
      // The query automatically filters by user_id due to Hasura permissions
      const response = await nhost.graphql.request<GetTodos>({
        query: `
          query GetTodos {
            todos(order_by: { created_at: desc }) {
              id
              title
              details
              completed
              created_at
              updated_at
              user_id
            }
          }
        `,
      });

      // Check for GraphQL errors in the response body
      if (response.body.errors) {
        throw new Error(
          response.body.errors[0]?.message || "Failed to fetch todos",
        );
      }

      // Extract todos from the GraphQL response data
      setTodos(response.body?.data?.todos || []);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to fetch todos");
    } finally {
      setLoading(false);
    }
  }, [nhost.graphql]);

  const addTodo = async () => {
    if (!newTodoTitle.trim()) return;

    try {
      setAddingTodo(true);
      // Execute GraphQL mutation to insert a new todo
      // user_id is automatically set by Hasura based on JWT token
      const response = await nhost.graphql.request<InsertTodo>({
        query: `
          mutation InsertTodo($title: String!, $details: String) {
            insert_todos_one(object: { title: $title, details: $details }) {
              id
              title
              details
              completed
              created_at
              updated_at
              user_id
            }
          }
        `,
        variables: {
          title: newTodoTitle.trim(),
          details: newTodoDetails.trim() || null,
        },
      });

      if (response.body.errors) {
        throw new Error(
          response.body.errors[0]?.message || "Failed to add todo",
        );
      }

      if (!response.body?.data?.insert_todos_one) {
        throw new Error("Failed to add todo");
      }
      setTodos([response.body?.data?.insert_todos_one, ...todos]);
      setNewTodoTitle("");
      setNewTodoDetails("");
      setShowAddForm(false);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to add todo");
      Alert.alert("Error", err instanceof Error ? err.message : "Failed to add todo");
    } finally {
      setAddingTodo(false);
    }
  };

  const updateTodo = async (
    id: string,
    updates: Partial<Pick<Todo, "title" | "details" | "completed">>,
  ) => {
    try {
      setUpdatingTodos(prev => new Set([...prev, id]));
      // Execute GraphQL mutation to update an existing todo by primary key
      // Hasura permissions ensure users can only update their own todos
      const response = await nhost.graphql.request<UpdateTodo>({
        query: `
          mutation UpdateTodo($id: uuid!, $updates: todos_set_input!) {
            update_todos_by_pk(pk_columns: { id: $id }, _set: $updates) {
              id
              title
              details
              completed
              created_at
              updated_at
              user_id
            }
          }
        `,
        variables: {
          id,
          updates,
        },
      });

      if (response.body.errors) {
        throw new Error(
          response.body.errors[0]?.message || "Failed to update todo",
        );
      }

      if (!response.body?.data?.update_todos_by_pk) {
        throw new Error("Failed to update todo");
      }

      const updatedTodo = response.body?.data?.update_todos_by_pk;
      if (updatedTodo) {
        setTodos(todos.map((todo) => (todo.id === id ? updatedTodo : todo)));
      }
      setEditingTodo(null);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to update todo");
      Alert.alert("Error", err instanceof Error ? err.message : "Failed to update todo");
    } finally {
      setUpdatingTodos(prev => {
        const newSet = new Set(prev);
        newSet.delete(id);
        return newSet;
      });
    }
  };

  const deleteTodo = async (id: string) => {
    Alert.alert(
      "Delete Todo",
      "Are you sure you want to delete this todo?",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Delete",
          style: "destructive",
          onPress: async () => {
            try {
              setUpdatingTodos(prev => new Set([...prev, id]));
              // Execute GraphQL mutation to delete a todo by primary key
              // Hasura permissions ensure users can only delete their own todos
              const response = await nhost.graphql.request({
                query: `
                  mutation DeleteTodo($id: uuid!) {
                    delete_todos_by_pk(id: $id) {
                      id
                    }
                  }
                `,
                variables: {
                  id,
                },
              });

              if (response.body.errors) {
                throw new Error(
                  response.body.errors[0]?.message || "Failed to delete todo",
                );
              }

              setTodos(todos.filter((todo) => todo.id !== id));
              setError(null);
            } catch (err) {
              setError(err instanceof Error ? err.message : "Failed to delete todo");
              Alert.alert("Error", err instanceof Error ? err.message : "Failed to delete todo");
            } finally {
              setUpdatingTodos(prev => {
                const newSet = new Set(prev);
                newSet.delete(id);
                return newSet;
              });
            }
          },
        },
      ]
    );
  };

  const toggleComplete = async (todo: Todo) => {
    await updateTodo(todo.id, { completed: !todo.completed });
  };

  const saveEdit = async () => {
    if (!editingTodo) return;
    await updateTodo(editingTodo.id, {
      title: editingTodo.title,
      details: editingTodo.details,
    });
  };

  const toggleTodoExpansion = (todoId: string) => {
    const newExpanded = new Set(expandedTodos);
    if (newExpanded.has(todoId)) {
      newExpanded.delete(todoId);
    } else {
      newExpanded.add(todoId);
    }
    setExpandedTodos(newExpanded);
  };

  // Fetch todos when user session is available
  // The session contains the JWT token needed for GraphQL authentication
  useEffect(() => {
    if (session) {
      fetchTodos();
    }
  }, [session, fetchTodos]);

  if (!session) {
    return null; // Will redirect to sign in
  }

  const renderTodoItem = ({ item: todo }: { item: Todo }) => {
    const isUpdating = updatingTodos.has(todo.id);
    const isExpanded = expandedTodos.has(todo.id);

    return (
      <View style={[commonStyles.todoCard, todo.completed && commonStyles.todoCompleted]}>
        {editingTodo?.id === todo.id ? (
          <View style={commonStyles.todoEditForm}>
            <Text style={commonStyles.inputLabel}>Title</Text>
            <TextInput
              style={commonStyles.input}
              value={editingTodo.title}
              onChangeText={(text) =>
                setEditingTodo({
                  ...editingTodo,
                  title: text,
                })
              }
              placeholder="Enter todo title"
            />
            <Text style={commonStyles.inputLabel}>Details</Text>
            <TextInput
              style={[commonStyles.input, commonStyles.textArea]}
              value={editingTodo.details || ""}
              onChangeText={(text) =>
                setEditingTodo({
                  ...editingTodo,
                  details: text,
                })
              }
              placeholder="Enter details (optional)"
              multiline
              numberOfLines={3}
            />
            <View style={commonStyles.buttonGroup}>
              <TouchableOpacity
                style={[commonStyles.button, commonStyles.primaryButton]}
                onPress={saveEdit}
                disabled={isUpdating}
              >
                <Text style={commonStyles.buttonText}>
                  {isUpdating ? "Saving..." : "Save"}
                </Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={[commonStyles.button, commonStyles.secondaryButton]}
                onPress={() => setEditingTodo(null)}
              >
                <Text style={[commonStyles.buttonText, commonStyles.secondaryButtonText]}>
                  Cancel
                </Text>
              </TouchableOpacity>
            </View>
          </View>
        ) : (
          <View>
            <View style={commonStyles.todoHeader}>
              <TouchableOpacity
                style={commonStyles.todoTitleContainer}
                onPress={() => toggleTodoExpansion(todo.id)}
              >
                <Text
                  style={[
                    commonStyles.todoTitle,
                    todo.completed && commonStyles.todoTitleCompleted,
                  ]}
                >
                  {todo.title}
                </Text>
              </TouchableOpacity>
              <View style={commonStyles.todoActions}>
                <TouchableOpacity
                  style={[commonStyles.actionButton, commonStyles.completeButton]}
                  onPress={() => toggleComplete(todo)}
                  disabled={isUpdating}
                >
                  <Text style={commonStyles.actionButtonText}>
                    {isUpdating ? "⌛" : todo.completed ? "↶" : "✓"}
                  </Text>
                </TouchableOpacity>
                <TouchableOpacity
                  style={[commonStyles.actionButton, commonStyles.editButton]}
                  onPress={() => setEditingTodo(todo)}
                >
                  <Text style={commonStyles.actionButtonText}>✏️</Text>
                </TouchableOpacity>
                <TouchableOpacity
                  style={[commonStyles.actionButton, commonStyles.deleteButton]}
                  onPress={() => deleteTodo(todo.id)}
                  disabled={isUpdating}
                >
                  <Text style={commonStyles.actionButtonText}>🗑️</Text>
                </TouchableOpacity>
              </View>
            </View>
            {isExpanded && (
              <View style={commonStyles.todoDetails}>
                {todo.details && (
                  <Text
                    style={[
                      commonStyles.todoDescription,
                      todo.completed && commonStyles.todoDescriptionCompleted,
                    ]}
                  >
                    {todo.details}
                  </Text>
                )}
                <View style={commonStyles.todoMeta}>
                  <Text style={commonStyles.metaText}>
                    Created: {new Date(todo.created_at).toLocaleString()}
                  </Text>
                  <Text style={commonStyles.metaText}>
                    Updated: {new Date(todo.updated_at).toLocaleString()}
                  </Text>
                  {todo.completed && (
                    <View style={commonStyles.completionBadge}>
                      <Text style={commonStyles.completionText}>✅ Completed</Text>
                    </View>
                  )}
                </View>
              </View>
            )}
          </View>
        )}
      </View>
    );
  };

  return (
    <ProtectedScreen>
      <Stack.Screen options={{ title: "My Todos" }} />
      <ScrollView style={commonStyles.container}>
        <View style={commonStyles.pageHeader}>
          <Text style={commonStyles.pageTitle}>My Todos</Text>
          {!showAddForm && (
            <TouchableOpacity
              style={commonStyles.addButton}
              onPress={() => setShowAddForm(true)}
            >
              <Text style={commonStyles.addButtonText}>+</Text>
            </TouchableOpacity>
          )}
        </View>

        {error && (
          <View style={commonStyles.errorContainer}>
            <Text style={commonStyles.errorText}>Error: {error}</Text>
          </View>
        )}

        {showAddForm && (
          <View style={commonStyles.card}>
            <Text style={commonStyles.cardTitle}>Add New Todo</Text>
            <View style={commonStyles.formFields}>
              <View style={commonStyles.fieldGroup}>
                <Text style={commonStyles.inputLabel}>Title *</Text>
                <TextInput
                  style={commonStyles.input}
                  value={newTodoTitle}
                  onChangeText={setNewTodoTitle}
                  placeholder="What needs to be done?"
                />
              </View>
              <View style={commonStyles.fieldGroup}>
                <Text style={commonStyles.inputLabel}>Details</Text>
                <TextInput
                  style={[commonStyles.input, commonStyles.textArea]}
                  value={newTodoDetails}
                  onChangeText={setNewTodoDetails}
                  placeholder="Add some details (optional)..."
                  multiline
                  numberOfLines={3}
                />
              </View>
              <View style={commonStyles.buttonGroup}>
                <TouchableOpacity
                  style={[commonStyles.button, commonStyles.primaryButton]}
                  onPress={addTodo}
                  disabled={addingTodo || !newTodoTitle.trim()}
                >
                  <Text style={commonStyles.buttonText}>
                    {addingTodo ? "Adding..." : "Add Todo"}
                  </Text>
                </TouchableOpacity>
                <TouchableOpacity
                  style={[commonStyles.button, commonStyles.secondaryButton]}
                  onPress={() => {
                    setShowAddForm(false);
                    setNewTodoTitle("");
                    setNewTodoDetails("");
                  }}
                >
                  <Text style={[commonStyles.buttonText, commonStyles.secondaryButtonText]}>
                    Cancel
                  </Text>
                </TouchableOpacity>
              </View>
            </View>
          </View>
        )}

        {!showAddForm && (
          <View style={commonStyles.contentSection}>
            {loading ? (
              <View style={commonStyles.loadingContainer}>
                <ActivityIndicator size="large" color="#6366f1" />
                <Text style={commonStyles.loadingText}>Loading todos...</Text>
              </View>
            ) : todos.length === 0 ? (
              <View style={commonStyles.emptyState}>
                <Text style={commonStyles.emptyStateTitle}>No todos yet</Text>
                <Text style={commonStyles.emptyStateText}>
                  Create your first todo to get started!
                </Text>
              </View>
            ) : (
              <FlatList
                data={todos}
                renderItem={renderTodoItem}
                keyExtractor={(item) => item.id}
                showsVerticalScrollIndicator={false}
                contentContainerStyle={commonStyles.listContainer}
              />
            )}
          </View>
        )}
      </ScrollView>
    </ProtectedScreen>
  );
}
