// templates/react/frontend/src/pages/Protected.tsx
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { type FormEvent, useEffect, useState } from 'react';
import { useNavigate } from 'react-router';
import { graphql } from '@/gql';
import { gqlRequest } from '../lib/graphql';
import { useAuth } from '../lib/nhost/AuthProvider';

const GetTodos = graphql(`
  query GetTodos {
    todos {
      id
      title
      completed
      created_at
      user_id
    }
  }
`);

const CreateTodo = graphql(`
  mutation CreateTodo($title: String!) {
    insert_todos_one(object: { title: $title }) {
      id
      title
      completed
      created_at
      user_id
    }
  }
`);

const todosQueryKey = ['todos'] as const;

export default function Protected() {
  const { nhost, session } = useAuth();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [title, setTitle] = useState('');

  useEffect(() => {
    if (!session) {
      navigate('/signin');
    }
  }, [session, navigate]);

  const todos = useQuery({
    queryKey: todosQueryKey,
    queryFn: () => gqlRequest(nhost, GetTodos, {}),
    enabled: !!session,
  });

  const createTodo = useMutation({
    mutationFn: (newTitle: string) =>
      gqlRequest(nhost, CreateTodo, { title: newTitle }),
    onSuccess: async () => {
      setTitle('');
      await queryClient.invalidateQueries({ queryKey: todosQueryKey });
    },
  });

  const signOut = async () => {
    if (session) {
      await nhost.auth.signOut({ refreshToken: session.refreshToken });
    }
    navigate('/');
  };

  const submit = (event: FormEvent) => {
    event.preventDefault();
    const trimmed = title.trim();
    if (trimmed) {
      createTodo.mutate(trimmed);
    }
  };

  if (!session) {
    return null;
  }

  return (
    <div className="stack">
      <div className="row between">
        <h1>Your todos</h1>
        <button className="button ghost" type="button" onClick={signOut}>
          Sign out
        </button>
      </div>
      <p className="muted">
        These rows are protected by per-user GraphQL permissions.
      </p>

      <form className="row" onSubmit={submit}>
        <label className="field grow">
          <span className="visually-hidden">New todo</span>
          <input
            value={title}
            onChange={(event) => setTitle(event.target.value)}
            placeholder="Ship something useful"
            disabled={createTodo.isPending}
          />
        </label>
        <button
          className="button"
          type="submit"
          disabled={createTodo.isPending || !title.trim()}
        >
          {createTodo.isPending ? 'Adding…' : 'Add todo'}
        </button>
      </form>

      {createTodo.error && <p className="error">Could not create the todo.</p>}
      {todos.isPending && <p className="muted">Loading todos…</p>}
      {todos.error && <p className="error">Could not load todos.</p>}
      {todos.data?.todos.length === 0 && (
        <p className="muted">No todos yet. Add your first one above.</p>
      )}

      <ul className="list">
        {todos.data?.todos.map((todo) => (
          <li key={String(todo.id)} className={todo.completed ? 'done' : ''}>
            {todo.title}
          </li>
        ))}
      </ul>
    </div>
  );
}

// templates/svelte/frontend/src/routes/protected/+page.svelte
<script lang="ts">
import type { ResultOf } from '@graphql-typed-document-node/core';
import { onMount } from 'svelte';
import { get } from 'svelte/store';
import { goto } from '$app/navigation';
import { graphql } from '$gql';
import { gqlRequest } from '$lib/graphql';
import { nhost, session } from '$lib/nhost/auth';

const GetTodos = graphql(`
  query GetTodos {
    todos {
      id
      title
      completed
      created_at
      user_id
    }
  }
`);

const CreateTodo = graphql(`
  mutation CreateTodo($title: String!) {
    insert_todos_one(object: { title: $title }) {
      id
      title
      completed
      created_at
      user_id
    }
  }
`);

type TodoList = ResultOf<typeof GetTodos>['todos'];

let todos = $state<TodoList>([]);
let title = $state('');
let loading = $state(true);
let submitting = $state(false);
let error = $state<string | null>(null);

async function load(): Promise<void> {
  loading = true;
  try {
    const data = await gqlRequest(nhost, GetTodos, {});
    todos = data.todos;
    error = null;
  } catch {
    error = 'Could not load todos.';
  } finally {
    loading = false;
  }
}

async function add(event: SubmitEvent): Promise<void> {
  event.preventDefault();
  const trimmed = title.trim();
  if (!trimmed) {
    return;
  }
  submitting = true;
  try {
    await gqlRequest(nhost, CreateTodo, { title: trimmed });
    title = '';
    await load();
  } catch {
    error = 'Could not create the todo.';
  } finally {
    submitting = false;
  }
}

async function signOut(): Promise<void> {
  const current = get(session);
  if (current) {
    await nhost.auth.signOut({ refreshToken: current.refreshToken });
  }
  goto('/');
}

onMount(() => {
  if (!get(session)) {
    goto('/signin');
    return;
  }
  void load();
});
</script>

<div class="stack">
  <div class="row between">
    <h1>Your todos</h1>
    <button class="button ghost" type="button" onclick={signOut}>Sign out</button>
  </div>
  <p class="muted">These rows are protected by per-user GraphQL permissions.</p>

  <form class="row" onsubmit={add}>
    <label class="field grow">
      <span class="visually-hidden">New todo</span>
      <input
        bind:value={title}
        placeholder="Ship something useful"
        disabled={submitting}
      />
    </label>
    <button class="button" type="submit" disabled={submitting || !title.trim()}>
      {submitting ? 'Adding…' : 'Add todo'}
    </button>
  </form>

  {#if error}<p class="error">{error}</p>{/if}
  {#if loading}
    <p class="muted">Loading todos…</p>
  {:else if todos.length === 0}
    <p class="muted">No todos yet. Add your first one above.</p>
  {/if}

  <ul class="list">
    {#each todos as todo (String(todo.id))}
      <li class:done={todo.completed}>{todo.title}</li>
    {/each}
  </ul>
</div>
