// examples/react-apollo/src/components/email-passwordless-form.tsx
import { Button, Input, Message } from 'rsuite'
import { useNavigate } from 'react-router-dom'
import { useSignInEmailPasswordless } from '@nhost/react'
import React, { useState, useEffect } from 'react'

export const EmailPasswordlessForm: React.FC = () => {
  const [email, setEmail] = useState('')
  const navigate = useNavigate()
  const { signInEmailPasswordless, isError, isSuccess, error } = useSignInEmailPasswordless(email, {
    redirectTo: '/profile'
  })
  const [showError, setShowError] = useState(true)
  useEffect(() => {
    setShowError(false)
  }, [email])

  useEffect(() => {
    if (isSuccess) {
      navigate('/sign-in/verification-email-sent')
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isSuccess])

  return (
    <div>
      <Input
        placeholder="Email Address"
        value={email}
        onChange={setEmail}
        size="lg"
        autoFocus
        style={{ marginBottom: '0.5em' }}
      />
      {showError && isError && (
        <Message showIcon type="error">
          {error?.message}
        </Message>
      )}
      <Button
        block
        appearance="primary"
        style={{ marginTop: '0.5em' }}
        onClick={() => {
          setShowError(true)
          signInEmailPasswordless()
        }}
      >
        Continue with email
      </Button>
    </div>
  )
}

// examples/vue-apollo/src/components/EmailPasswordlessForm.vue
<template>
  <div>
    <form @submit="submit">
      <v-text-field v-model="email" placeholder="Email Address" autofocus />
      <v-btn block color="primary" type="submit"> Continue with email </v-btn>
    </form>
    <error-snack-bar :error="error" />
    <v-dialog v-model="emailSentDialog">
      <v-card>
        <v-card-title>
          <span class="text-h5">Verification email sent</span>
        </v-card-title>
        <v-card-text>
          A email has been sent to {{ email }}. Please follow the link to sign in to the application.
        </v-card-text>
        <v-card-actions class="d-flex justify-center">
          <v-btn text @click="emailSentDialog = false">
            Close
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue'
import { useSignInEmailPasswordless } from '@nhost/vue'

const email = ref('')
const emailSentDialog = ref(false)

const { signInEmailPasswordless, error } = useSignInEmailPasswordless({
  redirectTo: '/#/profile'
})

const submit = async (e: Event) => {
  e.preventDefault()
  const { isSuccess } = await signInEmailPasswordless(email)
  if (isSuccess) {
    emailSentDialog.value = true
  }
}
</script>
