// examples/react-apollo/src/components/OauthLinks.tsx
import { FaFacebook, FaGithub, FaGoogle } from 'react-icons/fa/index.js'

import { useProviderLink } from '@nhost/react'

import AuthLink from './AuthLink'

export default function OauthLinks() {
  const { github, google, facebook } = useProviderLink({ redirectTo: window.location.origin })
  return (
    <>
      <AuthLink leftIcon={<FaGithub />} link={github} color="#333">
        Continue with GitHub
      </AuthLink>
      <AuthLink leftIcon={<FaGoogle />} link={google} color="#de5246">
        Continue with Google
      </AuthLink>
      <AuthLink leftIcon={<FaFacebook />} link={facebook} color="#3b5998">
        Continue with Facebook
      </AuthLink>
    </>
  )
}

// examples/vue-apollo/src/components/OAuthLinks.vue
<template>
  <v-btn class="my-1" block variant="contained-text" prepend-icon="mdi-github" color="white"
    style="background-color: #333" :href="github">
    Continue with GitHub
  </v-btn>
  <v-btn class="my-1" block variant="contained-text" prepend-icon="mdi-google" color="white"
    style="background-color: #de5246" :href="google">
    Continue with Google
  </v-btn>
  <v-btn class="my-1" block variant="contained-text" prepend-icon="mdi-facebook" color="white"
    style="background-color: #3b5998" :href="facebook">
    Continue with Facebook
  </v-btn>
</template>

<script lang="ts" setup>

import { useProviderLink } from '@nhost/vue'

const { github, google, facebook } = useProviderLink({ redirectTo: window.location.origin })
</script>
