// deprecated/examples/quickstarts/sveltekit/src/routes/auth/sign-in/pat/+page.svelte
<script>
	import Button from '$lib/components/Button.svelte'
	import Input from '$lib/components/Input.svelte'
	
	/** @type {import('./$types').Actions} */
	export let form;
</script>

<svelte:head>
	<title>Sign In</title>
</svelte:head>

<div class="max-w-xl mx-auto space-y-4">
  <h1 class="text-2xl font-semibold text-center">Sign in with a Personal Access Token</h1>
  
  {#if form?.error}
    <p class="mt-3 font-semibold text-center text-red-500">{form?.error}</p>
  {/if}
  
  <form class="max-w-xl mx-auto space-y-4" method='POST'>
    <Input label="PAT " id="pat" name="pat" required />
    <Button class='w-full' type="submit">Sign In</Button>
  </form>
</div>

// examples/quickstarts/nextjs-server-components/src/app/auth/sign-in/pat/page.tsx
'use client'

import { signInWithPAT } from '@actions'
import Input from '@components/input'
import SubmitButton from '@components/submit-button'
import { useState } from 'react'

export default function SignInWithPAT() {
  const [error, setError] = useState('')

  async function handleSignIn(formData: FormData) {
    const response = await signInWithPAT(formData)

    if (response?.error) {
      setError(response.error)
    }
  }

  return (
    <div className="flex flex-col items-center gap-4">
      <h1 className="text-2xl font-semibold text-center">Sign In with Personal Access Token</h1>

      {error && <p className="mt-3 font-semibold text-center text-red-500">{error}</p>}

      <form className="w-full max-w-lg space-y-5" action={handleSignIn}>
        <Input label="PAT" id="pat" name="pat" required />
        <SubmitButton type="submit" className="w-full">
          Sign In
        </SubmitButton>
      </form>
    </div>
  )
}
