// examples/tutorials/nhost-svelte-tutorial/src/routes/signup/+page.svelte
<script lang="ts">
import type { ErrorResponse } from '@nhost/nhost-js/auth';
import { generatePKCEPair } from '@nhost/nhost-js/auth';
import type { FetchError } from '@nhost/nhost-js/fetch';
import { goto } from '$app/navigation';
import { auth, nhost } from '$lib/nhost/auth';

let email = $state('');
let password = $state('');
let displayName = $state('');
let isLoading = $state(false);
let error = $state<string | null>(null);
let success = $state(false);

// If already authenticated, redirect to profile
$effect(() => {
  if ($auth.isAuthenticated) {
    void goto('/profile');
  }
});

async function handleSubmit(e: Event) {
  e.preventDefault();
  isLoading = true;
  error = null;
  success = false;

  try {
    // Generate PKCE pair and store verifier for email verification
    const { verifier, challenge } = await generatePKCEPair();
    localStorage.setItem('nhost_pkce_verifier', verifier);

    const response = await nhost.auth.signUpEmailPassword({
      email,
      password,
      options: {
        displayName,
        redirectTo: `${window.location.origin}/verify`,
      },
      codeChallenge: challenge,
    });

    if (response.body?.session) {
      // Successfully signed up and automatically signed in
      void goto('/profile');
    } else {
      // Verification email sent
      success = true;
    }
  } catch (err) {
    const fetchError = err as FetchError<ErrorResponse>;
    error = `An error occurred during sign up: ${fetchError.message}`;
  } finally {
    isLoading = false;
  }
}
</script>

{#if success}
  <div>
    <h1>Check Your Email</h1>
    <div class="success-message">
      <p>
        We've sent a verification link to <strong>{email}</strong>
      </p>
      <p>
        Please check your email and click the verification link to activate your account.
      </p>
    </div>
    <p>
      <a href="/signin">Back to Sign In</a>
    </p>
  </div>
{:else}
  <div>
    <h1>Sign Up</h1>

    <form onsubmit={handleSubmit} class="auth-form">
      <div class="auth-form-field">
        <label for="displayName">Display Name</label>
        <input
          id="displayName"
          type="text"
          bind:value={displayName}
          required
          class="auth-input"
        />
      </div>

      <div class="auth-form-field">
        <label for="email">Email</label>
        <input
          id="email"
          type="email"
          bind:value={email}
          required
          class="auth-input"
        />
      </div>

      <div class="auth-form-field">
        <label for="password">Password</label>
        <input
          id="password"
          type="password"
          bind:value={password}
          required
          minlength="8"
          class="auth-input"
        />
        <small class="help-text">Minimum 8 characters</small>
      </div>

      {#if error}
        <div class="auth-error">
          {error}
        </div>
      {/if}

      <button
        type="submit"
        disabled={isLoading}
        class="auth-button primary"
      >
        {isLoading ? "Creating Account..." : "Sign Up"}
      </button>
    </form>

    <div class="auth-links">
      <p>
        Already have an account? <a href="/signin">Sign In</a>
      </p>
    </div>
  </div>
{/if}

// examples/tutorials/nhost-vue-tutorial/src/views/SignUp.vue
<template>
  <div>
    <h1 v-if="!success">Sign Up</h1>
    <h1 v-else>Check Your Email</h1>

    <div v-if="success" class="success-message">
      <p>
        We've sent a verification link to <strong>{{ email }}</strong>
      </p>
      <p>
        Please check your email and click the verification link to activate your account.
      </p>
      <p>
        <router-link to="/signin">Back to Sign In</router-link>
      </p>
    </div>

    <form v-else @submit.prevent="handleSubmit" class="auth-form">
      <div class="auth-form-field">
        <label :for="displayNameId">Display Name</label>
        <input
          :id="displayNameId"
          type="text"
          v-model="displayName"
          required
          class="auth-input"
        />
      </div>

      <div class="auth-form-field">
        <label :for="emailId">Email</label>
        <input
          :id="emailId"
          type="email"
          v-model="email"
          required
          class="auth-input"
        />
      </div>

      <div class="auth-form-field">
        <label :for="passwordId">Password</label>
        <input
          :id="passwordId"
          type="password"
          v-model="password"
          required
          minlength="8"
          class="auth-input"
        />
        <small class="help-text">Minimum 8 characters</small>
      </div>

      <div v-if="error" class="auth-error">
        {{ error }}
      </div>

      <button
        type="submit"
        :disabled="isLoading"
        class="auth-button primary"
      >
        {{ isLoading ? "Creating Account..." : "Sign Up" }}
      </button>
    </form>

    <div v-if="!success" class="auth-links">
      <p>
        Already have an account? <router-link to="/signin">Sign In</router-link>
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { generatePKCEPair } from '@nhost/nhost-js/auth';
import { onMounted, ref, useId } from 'vue';
import { useRouter } from 'vue-router';
import { useAuth } from '../lib/nhost/auth';

const { nhost, isAuthenticated } = useAuth();
const router = useRouter();

const email = ref('');
const password = ref('');
const displayName = ref('');
const isLoading = ref(false);
const error = ref<string | null>(null);
const success = ref(false);

const displayNameId = useId();
const emailId = useId();
const passwordId = useId();

// Redirect authenticated users to profile
onMounted(() => {
  if (isAuthenticated.value) {
    router.push('/profile');
  }
});

const handleSubmit = async () => {
  isLoading.value = true;
  error.value = null;
  success.value = false;

  try {
    // Generate PKCE pair and store verifier for email verification
    const { verifier, challenge } = await generatePKCEPair();
    localStorage.setItem('nhost_pkce_verifier', verifier);

    const response = await nhost.auth.signUpEmailPassword({
      email: email.value,
      password: password.value,
      options: {
        displayName: displayName.value,
        redirectTo: `${window.location.origin}/verify`,
      },
      codeChallenge: challenge,
    });

    if (response.body?.session) {
      // Successfully signed up and automatically signed in
      router.push('/profile');
    } else {
      // Verification email sent
      success.value = true;
    }
  } catch (err) {
    const message = (err as Error).message || 'Unknown error';
    error.value = `An error occurred during sign up: ${message}`;
  } finally {
    isLoading.value = false;
  }
};
</script>
