// examples/react-apollo/src/components/OauthLinks.tsx
import { FaGithub, FaGoogle } from 'react-icons/fa/index.js'

import { useProviderLink } from '@nhost/react'

import AuthLink from './AuthLink'

export default function OauthLinks() {
  const { github, google } = useProviderLink({ redirectTo: window.location.origin })
  return (
    <>
      <AuthLink leftIcon={<FaGithub />} link={github} color="#333">
        Continue with GitHub
      </AuthLink>
      <AuthLink leftIcon={<FaGoogle />} link={google} color="#de5246">
        Continue with Google
      </AuthLink>
    </>
  )
}

// deprecated/examples/vue-apollo/src/components/OAuthLinks.vue
<template>
  <v-btn
    class="my-1"
    block
    variant="text"
    prepend-icon="mdi-github"
    color="white"
    style="background-color: #333"
    :href="github"
  >
    Continue with GitHub
  </v-btn>
</template>

<script lang="ts" setup>
import { useProviderLink } from '@nhost/vue'

const { github } = useProviderLink({ redirectTo: `${window.location.origin}/profile` })
</script>
