// examples/vue-apollo/src/views/Register.vue
<template>
  <div class="login-container">
    <h2>Register</h2>
    <form @submit="register">
      <label for="email">Email</label>
      <br />
      <input type="email" name="email" v-model="email" />
      <br /><br />
      <label for="password">Password</label>
      <br />
      <input type="password" name="password" v-model="password" />
      <br /><br />
      <button type="submit">Submit</button>
    </form>
  </div>
  <br />
  <router-link to="/login">Or login</router-link>
</template>

<script>
import { auth } from "../utils/nhost";
export default {
  data() {
    return {
      email: "",
      password: "",
    };
  },
  methods: {
    async register(event) {
      event.preventDefault();
      try {
        const result = await auth.register({
          email: this.$data.email,
          password: this.$data.password,
        });

        if (result.user) {
          this.$router.push("/");
        } else throw new Error("Register Unsuccessful");
      } catch (e) {
        alert(e);
      }
    },
  },
};
</script>

// examples/create-react-app-apollo/src/components/register.jsx
import React, { useState } from "react";
import { useHistory, Link } from "react-router-dom";

import { auth } from "utils/nhost";

export function Register() {
  const [displayName, setDisplayName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const history = useHistory();

  async function handleSubmit(e) {
    e.preventDefault();

    try {
      await auth.register({
        email,
        password,
        options: {
          userData: {
            display_name: displayName,
          },
        },
      });
    } catch (error) {
      console.log(error);
      return alert("Registration failed");
    }

    alert("Registration OK. Logging you in...");
    history.push("/");
  }

  return (
    <div>
      <div>Register</div>
      <div>
        <form onSubmit={handleSubmit}>
          <div>
            <input
              type="text"
              value={displayName}
              onChange={(e) => setDisplayName(e.target.value)}
              placeholder="Name"
              autoFocus
            />
          </div>
          <div>
            <input
              type="text"
              value={email}
              placeholder="Email"
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>
          <div>
            <input
              type="password"
              value={password}
              placeholder="Password"
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          <div>
            <button type="submit">Register</button>
          </div>
        </form>
      </div>
      <div>
        <Link to="/login">Login</Link>
      </div>
    </div>
  );
}
