// examples/nextjs-app-router/src/app/sign-in/page.tsx
'use client'

import Button from '@components/button'
import Input from '@components/input'
import { useSignInEmailPassword } from '@nhost/nextjs'
import { useRouter } from 'next/navigation'
import { ChangeEvent, SyntheticEvent, useState } from 'react'

export default function SignIn() {
  const router = useRouter()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  const { signInEmailPassword, isLoading, needsEmailVerification, isError, error, isSuccess } =
    useSignInEmailPassword()

  const handleOnSubmit = async (e: SyntheticEvent) => {
    e.preventDefault()
    await signInEmailPassword(email, password)
  }

  const disableForm = isLoading || needsEmailVerification

  if (isSuccess) {
    router.push('/protected')
  }

  return (
    <>
      <h1 className="text-2xl font-semibold text-center">Sign In</h1>

      {isError && error && (
        <p className="mt-3 font-semibold text-center text-red-500">{error.message}</p>
      )}

      <form className="space-y-5" onSubmit={handleOnSubmit}>
        <Input
          label="Email"
          id="email"
          name="email"
          type="email"
          value={email}
          required
          onChange={(e: ChangeEvent<HTMLInputElement>) => setEmail(e.target.value)}
          disabled={disableForm}
        />

        <Input
          label="Password"
          id="password"
          name="password"
          type="password"
          value={password}
          required
          onChange={(e: ChangeEvent<HTMLInputElement>) => setPassword(e.target.value)}
          disabled={disableForm}
        />

        <Button type="submit">Sign In</Button>
      </form>
    </>
  )
}

// examples/sveltekit/src/routes/sign-in/+page.svelte
<script>
	import Input from '$lib/components/Input.svelte';
	import Button from '$lib/components/Button.svelte';
	import { goto, invalidate } from '$app/navigation';

	export let data;
	let { nhost } = data;

	/** @type {string}*/
	let email;

	/** @type {string}*/
	let password;

	/** @type {import('@nhost/nhost-js').AuthErrorPayload | null} */
	let error;

	const handleSignIn = async () => {
		const { error: signInError } = await nhost.auth.signIn({
			email,
			password
		});

		error = signInError;

		if (!error) {
			await invalidate('nhost:auth');
			await goto('/protected');
		}
	};
</script>

<svelte:head>
	<title>Sign In</title>
</svelte:head>

<h1 class="text-2xl font-semibold text-center">Sign In</h1>

{#if error}
	<p class="mt-3 font-semibold text-center text-red-500">{error.message}</p>
{/if}

<form class="space-y-5" on:submit={handleSignIn}>
	<Input label="Email" id="email" name="email" type="email" bind:value={email} required />

	<Input
		label="Password"
		id="password"
		name="password"
		type="password"
		bind:value={password}
		required
	/>

	<Button type="submit">Sign In</Button>
</form>
