// examples/vue-apollo/src/views/Login.vue
<template>
  <div class="login login-container">
    <h2>Login</h2>
    <form @submit="sendLoginRequest">
      <label for="email">Email</label>
      <br />
      <input type="text" name="email" v-model="email" />
      <br />
      <br />
      <label for="email">Password</label>
      <br />
      <input type="password" name="password" v-model="password" />
      <br />
      <br />
      <button>Submit</button>
    </form>
  </div>
  <br />
  <router-link to="/register">Or register</router-link>
</template>

<script>
import { ref } from "@vue/reactivity";
import { auth } from "../utils/nhost.js";
import { useRouter } from "vue-router";

export default {
  setup() {
    let email = ref("");
    let password = ref("");

    const router = useRouter();

    const sendLoginRequest = async (event) => {
      event.preventDefault();

      const authResult = await auth.login({
        email: email.value,
        password: password.value,
      });

      if (authResult.user) {
        router.push("/");
      } else {
        alert("Incorrect login.");
      }
    };

    return {
      email,
      password,
      sendLoginRequest,
    };
  },
};
</script>

// examples/nhost-vitedge/src/pages/Login.jsx
import React, { useState } from "react";
import { useHistory, Link } from "react-router-dom";

import { auth } from "../utils/nhost";

export function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const history = useHistory();

  async function handleSubmit(e) {
    e.preventDefault();

    try {
      await auth.login({ email, password });
    } catch (error) {
      console.log(error);
      return alert("login failed");
    }

    history.push("/");
  }

  return (
    <div>
      <div>Login</div>
      <div>
        <form onSubmit={handleSubmit}>
          <div>
            <input
              type="text"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="Email"
              autoFocus
            />
          </div>
          <div>
            <input
              type="password"
              value={password}
              placeholder="Password"
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          <div>
            <button type="submit">Login</button>
          </div>
        </form>
      </div>
      <div>
        <Link to="/register">Register</Link>
      </div>
    </div>
  );
}
