// examples/nextjs/pages/sign-up/index.tsx
import { NextPage } from 'next'
import React from 'react'
import { FaLock } from 'react-icons/fa'

import { Divider } from '@mantine/core'

import AuthLink from '../../components/AuthLink'
import OAuthLinks from '../../components/OauthLinks'
import SignUpLayout from '../../layouts/SignUpLayout'

export const SignUpPage: NextPage = () => {
  return (
    <SignUpLayout title="Sign Up">
      <OAuthLinks />
      <Divider my="sm" />
      <AuthLink icon={<FaLock />} variant="outline" link="/sign-up/passwordless">
        Continue with passwordless email
      </AuthLink>
      <AuthLink variant="subtle" link="/sign-up/email-password">
        Continue with email + password
      </AuthLink>
    </SignUpLayout>
  )
}

export default SignUpPage

// examples/vue-apollo/src/pages/sign-up/Main.vue
<template>
  <Links />
  <v-divider class="my-4" />
  <v-btn class="my-1" block variant="outlined" prepend-icon="mdi-lock" color="primary" to="/signup/passwordless">
    Continue with passwordless email
  </v-btn>
  <v-btn class="my-1" block variant="text" color="primary" to="/signup/email-password">Continue with email + password </v-btn>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import Links from '../../components/OAuthLinks.vue'
export default defineComponent({
  components: {
    Links
  },
  setup() {
    return {}
  }
})
</script>
