// templates/vue/frontend/src/auth/password/reset/ResetPasswordForm.vue
<script setup lang="ts">
import { ref, useId } from 'vue';
import { setNewPassword } from '@/auth/password/actions';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useAuth } from '@/lib/nhost/auth';

const pending = defineModel<boolean>('pending', { default: false });
const emit = defineEmits<{ changed: [] }>();

const { nhost } = useAuth();
const passwordId = useId();

const password = ref('');
const error = ref<string | undefined>();

const handleSubmit = async (): Promise<void> => {
  error.value = undefined;
  pending.value = true;
  try {
    const result = await setNewPassword(nhost, password.value);
    if (result.error) {
      error.value = result.error;
      return;
    }

    emit('changed');
  } catch (err) {
    console.error('Error changing the password:', err);
    error.value = 'The request did not reach the server. Try again.';
  } finally {
    pending.value = false;
  }
};
</script>

<template>
  <form class="flex flex-col gap-4" @submit.prevent="handleSubmit">
    <div class="flex flex-col gap-2">
      <Label :for="passwordId">New password</Label>
      <Input
        :id="passwordId"
        v-model="password"
        type="password"
        autocomplete="new-password"
        required
        :disabled="pending"
      />
    </div>

    <p v-if="error" role="alert" class="text-destructive text-sm">
      {{ error }}
    </p>

    <Button type="submit" :disabled="pending || !password">
      {{ pending ? 'Saving…' : 'Save the new password' }}
    </Button>
  </form>
</template>

// templates/nextjs/frontend/src/app/auth/password/reset/ResetPasswordForm.tsx
'use client';

import { type FormEvent, use, useId, useState } from 'react';
import { setNewPassword } from '@/app/auth/password/actions';
import { PasswordChangedContext } from '@/app/auth/password/reset/PasswordChanged';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

export default function ResetPasswordForm() {
  const onChanged = use(PasswordChangedContext);
  const passwordId = useId();
  const confirmId = useId();

  const [password, setPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [error, setError] = useState<string | undefined>();
  const [isSaving, setIsSaving] = useState(false);

  const handleSubmit = async (event: FormEvent): Promise<void> => {
    event.preventDefault();
    setError(undefined);

    if (password !== confirm) {
      setError('The two passwords do not match.');
      return;
    }

    setIsSaving(true);
    try {
      const result = await setNewPassword(password);
      if (result.error) {
        setError(result.error);
        return;
      }

      onChanged();
    } catch (err) {
      console.error('Error changing the password:', err);
      setError('The request did not reach the server. Try again.');
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <form className="flex flex-col gap-4" onSubmit={handleSubmit}>
      <div className="flex flex-col gap-2">
        <Label htmlFor={passwordId}>New password</Label>
        <Input
          id={passwordId}
          type="password"
          autoComplete="new-password"
          required
          value={password}
          onChange={(event) => setPassword(event.target.value)}
          disabled={isSaving}
        />
      </div>

      <div className="flex flex-col gap-2">
        <Label htmlFor={confirmId}>Confirm new password</Label>
        <Input
          id={confirmId}
          type="password"
          autoComplete="new-password"
          required
          value={confirm}
          onChange={(event) => setConfirm(event.target.value)}
          disabled={isSaving}
        />
      </div>

      {error ? (
        <p role="alert" className="text-destructive text-sm">
          {error}
        </p>
      ) : null}

      <Button type="submit" disabled={isSaving}>
        {isSaving ? 'Saving…' : 'Save password'}
      </Button>
    </form>
  );
}
