// examples/nextjs/pages/sign-in/email-password.tsx
import { NextPage } from 'next'
import { useRouter } from 'next/router'
import { useState } from 'react'

import { Button, Divider, PasswordInput, SimpleGrid, TextInput } from '@mantine/core'
import { showNotification } from '@mantine/notifications'
import { useSignInEmailPassword } from '@nhost/nextjs'

import AuthLink from '../../components/AuthLink'
import SignInLayout from '../../layouts/SignInLayout'

export const SignInPasswordPage: NextPage = () => {
  const router = useRouter()
  const { signInEmailPassword } = useSignInEmailPassword()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const signIn = async () => {
    const result = await signInEmailPassword(email, password)
    if (result.isError) {
      showNotification({
        color: 'red',
        title: 'Error',
        message: result.error.message
      })
    } else if (result.needsEmailVerification) {
      showNotification({
        color: 'red',
        title: 'Error',
        message: 'Email is not verified'
      })
    } else {
      router.replace('/')
    }
  }
  return (
    <SignInLayout title="Email + password Sign In">
      <SimpleGrid cols={1} spacing={6}>
        <TextInput
          type="email"
          placeholder="Email Address"
          value={email}
          onChange={(e) => setEmail(e.currentTarget.value)}
        />
        <PasswordInput
          placeholder="Password"
          value={password}
          onChange={(e) => setPassword(e.currentTarget.value)}
        />
        <Button fullWidth onClick={signIn}>
          Continue with email + password
        </Button>
      </SimpleGrid>
      <Divider />
      <AuthLink link="/sign-in" variant="white">
        &#8592; Other Login Options
      </AuthLink>
    </SignInLayout>
  )
}

export default SignInPasswordPage

// examples/vue-apollo/src/pages/sign-in/EmailPassword.vue
<template>
  <v-text-field v-model="email" label="Email" />
  <v-text-field v-model="password" label="Password" type="password" />
  <div v-if="error">{{ error.message }}</div>
  <v-btn block color="primary" class="my-1" @click="signIn">Sign in</v-btn>
  <v-btn class="my-1" block variant="text" color="primary" to="/signin"
    >&#8592; Other Login Options</v-btn
  >
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'
import { useSignInEmailPassword } from '@nhost/vue'
import { useRouter } from 'vue-router'

export default defineComponent({
  setup() {
    const email = ref('')
    const password = ref('')

    const router = useRouter()
    const { signInEmailPassword, error } = useSignInEmailPassword()
    const signIn = async () => {
      const { isSuccess } = await signInEmailPassword(email.value, password.value)
      if (isSuccess) {
        router.replace('/')
      }
    }

    return {
      email,
      error,
      password,
      signIn
    }
  }
})
</script>
