// examples/react-apollo/src/sign-in/email-passwordless.tsx
import { Button } from 'rsuite'
import { NavLink } from 'react-router-dom'
import React from 'react'
import { EmailPasswordlessForm } from '../components/email-passwordless-form'
export const EmailPasswordless: React.FC = () => {
  return (
    <div>
      <EmailPasswordlessForm />
      <Button as={NavLink} to="/sign-up" block appearance="link">
        &#8592; Other Login Options
      </Button>
    </div>
  )
}

// examples/vue-apollo/src/pages/sign-in/EmailPasswordless.vue
<template>
  <Form />
  <v-btn class="my-1" block variant="text" color="primary" to="/signin"
    >&#8592; Other Login Options</v-btn
  >
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import Form from '../../components/EmailPasswordlessForm.vue'

export default defineComponent({
  components: {
    Form
  }
})
</script>
