// examples/demos/vue-demo/src/components/profile/ChangePassword.vue
<template>
  <div class="glass-card p-8 mb-6">
    <h3 class="text-xl mb-4">Change Password</h3>

    <div v-if="success" class="alert alert-success mb-4">
      Password changed successfully!
    </div>

    <div v-if="error" class="alert alert-error mb-4">{{ error }}</div>

    <form @submit.prevent="handleSubmit">
      <div class="mb-4">
        <label for="new-password" class="block text-sm font-medium mb-1">
          New Password
        </label>
        <input
          id="new-password"
          type="password"
          v-model="newPassword"
          class="w-full p-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
          required
          minlength="3"
          :disabled="isLoading"
        />
      </div>

      <div class="mb-6">
        <label for="confirm-password" class="block text-sm font-medium mb-1">
          Confirm Password
        </label>
        <input
          id="confirm-password"
          type="password"
          v-model="confirmPassword"
          class="w-full p-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
          required
          :disabled="isLoading"
        />
      </div>

      <button
        type="submit"
        :disabled="isLoading"
        class="btn btn-primary w-full"
      >
        {{ isLoading ? "Updating..." : "Change Password" }}
      </button>
    </form>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useAuth } from "../../lib/nhost/auth";
import { type ErrorResponse } from "@nhost/nhost-js/auth";
import { type FetchError } from "@nhost/nhost-js/fetch";

const { nhost } = useAuth();

const newPassword = ref<string>("");
const confirmPassword = ref<string>("");
const isLoading = ref<boolean>(false);
const error = ref<string>("");
const success = ref<boolean>(false);

const handleSubmit = async (): Promise<void> => {
  // Reset states
  error.value = "";
  success.value = false;

  // Validate passwords
  if (newPassword.value.length < 3) {
    error.value = "Password must be at least 3 characters long";
    return;
  }

  if (newPassword.value !== confirmPassword.value) {
    error.value = "Passwords do not match";
    return;
  }

  isLoading.value = true;

  try {
    // Use the changeUserPassword method from the SDK
    await nhost.auth.changeUserPassword({
      newPassword: newPassword.value,
    });
    success.value = true;
    newPassword.value = "";
    confirmPassword.value = "";
  } catch (err) {
    const errorObj = err as FetchError<ErrorResponse>;
    error.value = `An error occurred while changing the password: ${errorObj.message}`;
  } finally {
    isLoading.value = false;
  }
};
</script>

// examples/demos/react-demo/src/components/ChangePassword.tsx
import type { ErrorResponse } from "@nhost/nhost-js/auth";
import type { FetchError } from "@nhost/nhost-js/fetch";
import { type JSX, useState } from "react";
import { useAuth } from "../lib/nhost/AuthProvider";

export default function ChangePassword(): JSX.Element {
  const [newPassword, setNewPassword] = useState<string>("");
  const [confirmPassword, setConfirmPassword] = useState<string>("");
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string>("");
  const [success, setSuccess] = useState<boolean>(false);
  const { nhost } = useAuth();

  const handleSubmit = async (
    e: React.FormEvent<HTMLFormElement>,
  ): Promise<void> => {
    e.preventDefault();

    // Reset states
    setError("");
    setSuccess(false);

    // Validate passwords
    if (newPassword.length < 3) {
      setError("Password must be at least 3 characters long");
      return;
    }

    if (newPassword !== confirmPassword) {
      setError("Passwords do not match");
      return;
    }

    setIsLoading(true);

    try {
      // Use the changeUserPassword method from the SDK
      await nhost.auth.changeUserPassword({
        newPassword,
      });
      setSuccess(true);
      setNewPassword("");
      setConfirmPassword("");
    } catch (err) {
      const error = err as FetchError<ErrorResponse>;
      setError(
        `An error occurred while changing the password: ${error.message}`,
      );
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="glass-card p-8 mb-6">
      <h3 className="text-xl mb-4">Change Password</h3>

      {success && (
        <div className="alert alert-success mb-4">
          Password changed successfully!
        </div>
      )}

      {error && <div className="alert alert-error mb-4">{error}</div>}

      <form onSubmit={handleSubmit}>
        <div className="mb-4">
          <label
            htmlFor="new-password"
            className="block text-sm font-medium mb-1"
          >
            New Password
          </label>
          <input
            id="new-password"
            type="password"
            value={newPassword}
            onChange={(e) => setNewPassword(e.target.value)}
            className="w-full p-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
            required
            minLength={3}
            disabled={isLoading}
          />
        </div>

        <div className="mb-6">
          <label
            htmlFor="confirm-password"
            className="block text-sm font-medium mb-1"
          >
            Confirm Password
          </label>
          <input
            id="confirm-password"
            type="password"
            value={confirmPassword}
            onChange={(e) => setConfirmPassword(e.target.value)}
            className="w-full p-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
            required
            disabled={isLoading}
          />
        </div>

        <button
          type="submit"
          disabled={isLoading}
          className="btn btn-primary w-full"
        >
          {isLoading ? "Updating..." : "Change Password"}
        </button>
      </form>
    </div>
  );
}
