// examples/demos/vue-demo/src/components/forms/MagicLinkForm.vue
<template>
  <div v-if="success" class="text-center">
    <p class="mb-4">Magic link sent! Check your email to sign in.</p>
    <button @click="success = false" class="btn btn-secondary">
      Try again
    </button>
  </div>
  <form v-else @submit.prevent="handleSubmit" class="space-y-5">
    <div>
      <label for="magic-email">Email</label>
      <input id="magic-email" type="email" v-model="email" required />
    </div>

    <div v-if="error" class="alert alert-error">{{ error }}</div>

    <button type="submit" class="btn btn-primary w-full" :disabled="isLoading">
      {{ isLoading ? "Sending..." : buttonLabel }}
    </button>
  </form>
</template>

<script setup lang="ts">
import type { ErrorResponse } from "@nhost/nhost-js/auth";
import { type FetchError } from "@nhost/nhost-js/fetch";
import { ref } from "vue";
import { useAuth } from "../../lib/nhost/auth";

interface Props {
  buttonLabel?: string;
}

withDefaults(defineProps<Props>(), {
  buttonLabel: "Send Magic Link",
});

const { nhost } = useAuth();

const email = ref<string>("");
const isLoading = ref<boolean>(false);
const success = ref<boolean>(false);
const error = ref<string | null>(null);

const handleSubmit = async () => {
  isLoading.value = true;
  error.value = null;

  try {
    await nhost.auth.signInPasswordlessEmail({
      email: email.value,
      options: {
        redirectTo: `${window.location.origin}/verify`,
      },
    });

    success.value = true;
  } catch (err) {
    const errorObj = err as FetchError<ErrorResponse>;
    error.value = `An error occurred while sending the magic link: ${errorObj.message}`;
  } finally {
    isLoading.value = false;
  }
};
</script>

// examples/demos/react-demo/src/components/MagicLinkForm.tsx
import type { ErrorResponse } from "@nhost/nhost-js/auth";
import type { FetchError } from "@nhost/nhost-js/fetch";
import React, { type JSX, useState } from "react";
import { useAuth } from "../lib/nhost/AuthProvider";

interface MagicLinkFormProps {
  buttonLabel?: string;
}

export default function MagicLinkForm({
  buttonLabel = "Send Magic Link",
}: MagicLinkFormProps): JSX.Element {
  const [email, setEmail] = useState<string>("");
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [success, setSuccess] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const { nhost } = useAuth();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);

    try {
      await nhost.auth.signInPasswordlessEmail({
        email,
        options: {
          redirectTo: `${window.location.origin}/verify`,
        },
      });

      setSuccess(true);
    } catch (err) {
      const error = err as FetchError<ErrorResponse>;
      setError(
        `An error occurred while sending the magic link: ${error.message}`,
      );
    } finally {
      setIsLoading(false);
    }
  };

  if (success) {
    return (
      <div className="text-center">
        <p className="mb-4">Magic link sent! Check your email to sign in.</p>
        <button
          type="button"
          onClick={() => setSuccess(false)}
          className="btn btn-secondary"
        >
          Try again
        </button>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-5">
      <div>
        <label htmlFor="magic-email">Email</label>
        <input
          id="magic-email"
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          required
        />
      </div>

      {error && <div className="alert alert-error">{error}</div>}

      <button
        type="submit"
        className="btn btn-primary w-full"
        disabled={isLoading}
      >
        {isLoading ? "Sending..." : buttonLabel}
      </button>
    </form>
  );
}
