// deprecated/examples/quickstarts/nextjs-server-components/src/app/auth/sign-up/webauthn/page.tsx
'use client'

import Input from '@components/input'
import SubmitButton from '@components/submit-button'
import { NhostClient } from '@nhost/nhost-js'
import Cookies from 'js-cookie'
import { useRouter } from 'next/navigation'
import { useState, type FormEvent } from 'react'

const NHOST_SESSION_KEY = 'nhostSession'

const nhost = new NhostClient({
  subdomain: process.env.NEXT_PUBLIC_NHOST_SUBDOMAIN || 'local',
  region: process.env.NEXT_PUBLIC_NHOST_REGION
})

export default function SignUpWebAuthn() {
  const router = useRouter()

  const [error, setError] = useState('')
  const [email, setEmail] = useState('')

  const handleSignUp = async (e: FormEvent) => {
    e.preventDefault()

    const { session, error } = await nhost.auth.signUp({
      email,
      securityKey: true
    })

    if (error) {
      setError(error.message)
    }

    console.log({
      handleSignUpSession: session
    })

    if (session) {
      Cookies.set(NHOST_SESSION_KEY, btoa(JSON.stringify(session)), { path: '/' })
      router.push('/protected/todos')
    }
  }

  return (
    <div className="flex flex-col items-center">
      <h1 className="text-2xl font-semibold text-center">Sign Up with a security key</h1>

      {error && <p className="mt-3 font-semibold text-center text-red-500">{error}</p>}

      <form className="w-full max-w-lg space-y-5" onSubmit={handleSignUp}>
        <Input
          label="Email"
          id="email"
          name="email"
          type="email"
          value={email}
          onChange={(e) => setEmail(e.currentTarget.value)}
          required
        />
        <SubmitButton type="submit" className="w-full">
          Sign Up
        </SubmitButton>
      </form>
    </div>
  )
}

// deprecated/examples/quickstarts/sveltekit/src/routes/auth/sign-up/webauthn/+page.svelte
<script>
  import { goto } from '$app/navigation'
  import { env } from '$env/dynamic/public'
  import Button from '$lib/components/Button.svelte'
  import { NHOST_SESSION_KEY } from '$lib/nhost'
  import { NhostClient } from '@nhost/nhost-js'
  import Cookies from 'js-cookie'

  /** @type {string} */
  let email

  /** @type {import('@nhost/nhost-js').AuthErrorPayload | null}*/
  let error

  const handleSubmit = async () => {
    const nhost = new NhostClient({
      subdomain: env.PUBLIC_NHOST_SUBDOMAIN,
      region: env.PUBLIC_NHOST_REGION
    })

    const { session, error: signInError } = await nhost.auth.signUp({ email, securityKey: true })

    if (session) {
      Cookies.set(NHOST_SESSION_KEY, btoa(JSON.stringify(session)), { path: '/' })
      goto('/protected/todos')
    } else {
      error = signInError
    }
  }
</script>

<svelte:head>
	<title>Sign Up</title>
</svelte:head>

<div class="max-w-xl mx-auto space-y-4">
  <h1 class="text-2xl font-semibold text-center">Sign up with a security key</h1>
  
  {#if error}
    <p class="mt-3 font-semibold text-center text-red-500">{error.message}</p>
  {/if}
  
  <form class="space-y-4" on:submit|preventDefault={handleSubmit}>
    <input
      bind:value={email}
      placeholder='email'
      class="block w-full p-3 border rounded-md border-slate-300 focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
    />
  
    <Button class='w-full' type="submit">Sign Up</Button>
  </form>
</div>
