// templates/react-native/frontend/app/signin.tsx
import { router } from 'expo-router';
import { useState } from 'react';
import {
  ActivityIndicator,
  ScrollView,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';
import { useAuth } from './lib/nhost/AuthProvider';
import { styles } from './styles';

export default function SignIn() {
  const { nhost } = useAuth();
  const [email, setEmail] = useState('');
  const [otp, setOtp] = useState('');
  const [sent, setSent] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const sendCode = async () => {
    setLoading(true);
    setError(null);
    try {
      await nhost.auth.signInOTPEmail({ email });
      setSent(true);
    } catch (err) {
      setError(`Could not send the code: ${(err as Error).message}`);
    } finally {
      setLoading(false);
    }
  };

  const verify = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await nhost.auth.verifySignInOTPEmail({ email, otp });
      if (response.body?.session) {
        router.replace('/protected');
      } else {
        setError('Invalid or expired code. Please try again.');
      }
    } catch (err) {
      setError(`Could not verify the code: ${(err as Error).message}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <ScrollView contentContainerStyle={styles.screen}>
      <Text style={styles.title}>Sign in</Text>
      <Text style={styles.muted}>
        Enter your email and we'll send a one-time code. While running locally,
        the email with the code is captured by the local mail viewer.
      </Text>

      <View style={styles.card}>
        {sent ? (
          <>
            <Text style={styles.label}>Code sent to {email}</Text>
            <TextInput
              style={styles.input}
              value={otp}
              onChangeText={setOtp}
              placeholder="123456"
              keyboardType="number-pad"
              autoComplete="one-time-code"
            />
            <TouchableOpacity
              style={styles.button}
              onPress={verify}
              disabled={loading || !otp}
            >
              {loading ? (
                <ActivityIndicator color="#ffffff" />
              ) : (
                <Text style={styles.buttonText}>Verify</Text>
              )}
            </TouchableOpacity>
          </>
        ) : (
          <>
            <Text style={styles.label}>Email</Text>
            <TextInput
              style={styles.input}
              value={email}
              onChangeText={setEmail}
              placeholder="you@example.com"
              keyboardType="email-address"
              autoCapitalize="none"
              autoComplete="email"
            />
            <TouchableOpacity
              style={styles.button}
              onPress={sendCode}
              disabled={loading || !email}
            >
              {loading ? (
                <ActivityIndicator color="#ffffff" />
              ) : (
                <Text style={styles.buttonText}>Send code</Text>
              )}
            </TouchableOpacity>
          </>
        )}

        {error ? <Text style={styles.error}>{error}</Text> : null}
      </View>
    </ScrollView>
  );
}

// templates/svelte/frontend/src/routes/signin/+page.svelte
<script lang="ts">
import { goto } from '$app/navigation';
import { nhost } from '$lib/nhost/auth';

let email = $state('');
let otp = $state('');
let sent = $state(false);
let loading = $state(false);
let error = $state<string | null>(null);

async function sendCode(): Promise<void> {
  loading = true;
  error = null;
  try {
    await nhost.auth.signInOTPEmail({ email });
    sent = true;
  } catch (err) {
    error = `Could not send the code: ${(err as Error).message}`;
  } finally {
    loading = false;
  }
}

async function verify(): Promise<void> {
  loading = true;
  error = null;
  try {
    const response = await nhost.auth.verifySignInOTPEmail({ email, otp });
    if (response.body?.session) {
      goto('/protected');
    } else {
      error = 'Invalid or expired code. Please try again.';
    }
  } catch (err) {
    error = `Could not verify the code: ${(err as Error).message}`;
  } finally {
    loading = false;
  }
}

function onSubmit(event: SubmitEvent): void {
  event.preventDefault();
  if (sent) {
    void verify();
  } else {
    void sendCode();
  }
}
</script>

<div class="stack">
  <h1>Sign in</h1>
  <p class="muted">
    Enter your email and we'll send a one-time code. While running locally, the
    email with the code is captured by the local mail viewer.
  </p>

  <form class="card stack" onsubmit={onSubmit}>
    {#if sent}
      <label class="field">
        <span>Code sent to {email}</span>
        <input
          bind:value={otp}
          inputmode="numeric"
          placeholder="123456"
          autocomplete="one-time-code"
        />
      </label>
    {:else}
      <label class="field">
        <span>Email</span>
        <input
          bind:value={email}
          type="email"
          placeholder="you@example.com"
          autocomplete="email"
          required
        />
      </label>
    {/if}

    <button
      class="button"
      type="submit"
      disabled={loading || (sent ? !otp : !email)}
    >
      {loading ? 'Working…' : sent ? 'Verify' : 'Send code'}
    </button>

    {#if error}<p class="error">{error}</p>{/if}
  </form>
</div>
