// templates/svelte/frontend/src/lib/components/LinkErrorNotice.svelte
<script lang="ts">
import { afterNavigate } from '$app/navigation';
import { useAuth } from '$lib/nhost/auth.svelte';

/**
 * Says why the link or provider redirect the visitor arrived from did not
 * sign them in. It sits above every page because that can be any of them: an
 * auth email or a provider comes back to wherever `next` said.
 *
 * It goes once the visitor moves on, except to sign-in: that is where trying
 * again starts, and where a protected page sends someone the link did not
 * sign in, so the reason still applies there. The `enter` navigation is the
 * app starting on the page they arrived on, not them leaving it.
 */
const auth = useAuth();

afterNavigate(({ type, from, to }) => {
  const path = to?.url.pathname;

  if (type !== 'enter' && path !== from?.url.pathname && path !== '/signin') {
    auth.clearLinkError();
  }
});
</script>

{#if auth.linkError}
  <p role="alert" class="mx-auto mb-6 max-w-md text-destructive text-sm">
    {auth.linkError}
  </p>
{/if}

// templates/react-native/frontend/src/components/LinkErrorNotice.tsx
import { View } from 'react-native';
import { Button } from '@/components/ui/Button';
import { ErrorText } from '@/components/ui/ErrorText';
import { useAuth } from '@/lib/nhost/AuthProvider';

/**
 * Says why the link or provider callback the user came back from did not sign
 * them in. It sits above every screen because that can be any of them: an
 * auth email or a provider comes back to wherever `next` said.
 *
 * A stack keeps the screens it passed through, so there is no single moment
 * the user leaves the one they arrived on. The notice goes when they dismiss
 * it, sign in, or come back from another link.
 */
export function LinkErrorNotice() {
  const { linkError, setLinkError } = useAuth();

  if (!linkError) {
    return null;
  }

  return (
    <View className="flex-row items-center justify-between gap-4">
      <View className="flex-1">
        <ErrorText>{linkError}</ErrorText>
      </View>
      <Button variant="link" size="link" onPress={() => setLinkError(null)}>
        Dismiss
      </Button>
    </View>
  );
}
