// templates/svelte/frontend/src/routes/protected/+page.svelte
<script lang="ts">
import { goto } from '$app/navigation';
import SignOutButton from '$lib/components/SignOutButton.svelte';
import * as Card from '$lib/components/ui/card';
import { useAuth } from '$lib/nhost/auth.svelte';
import { signInHref } from '$lib/signin/destination';

const auth = useAuth();

// This is a convenience, not a control. The check runs in the browser, so
// anyone can reach this component's markup by editing their own copy of the
// app. What protects data is the backend's permissions: the access token is
// what the API checks, and a request without a valid one gets nothing back
// no matter what this page renders.
const user = $derived(auth.session?.user);

// Nothing here guards against an unread session: the root `+layout.ts`
// awaits `startAuth` before this renders, so the stored session is already
// known and a signed-in visitor reloading is never bounced.
//
// An effect rather than a one-off check so that signing out in another tab
// moves this one too, and `replaceState` so the back button does not come
// straight back to a page that will bounce again.
$effect(() => {
  if (!user) {
    void goto(signInHref('/protected'), { replaceState: true });
  }
});
</script>

{#if user}
  <div class="mx-auto max-w-md">
    <Card.Root>
      <Card.Header>
        <Card.Title>Protected</Card.Title>
        <Card.Description>
          Only a signed-in visitor gets this far.
        </Card.Description>
      </Card.Header>
      <Card.Content class="flex flex-col gap-4">
        <dl class="grid grid-cols-[max-content_1fr] gap-x-4 gap-y-1 text-sm">
          <dt class="text-muted-foreground">Email</dt>
          <dd>{user.email ?? '—'}</dd>
          <dt class="text-muted-foreground">User id</dt>
          <dd class="font-mono text-xs">{user.id}</dd>
        </dl>
        <SignOutButton />
      </Card.Content>
    </Card.Root>
  </div>
{/if}

// templates/react-native/frontend/src/app/protected.tsx
import { Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { SignOutButton } from '@/components/SignOutButton';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/Card';
import { Redirect } from '@/lib/navigation';
import { useAuth } from '@/lib/nhost/AuthProvider';

export default function Protected() {
  const { session, isLoading } = useAuth();

  // Nothing is decided until the stored session has been read off disk, or a
  // signed-in user reopening the app would be bounced to sign-in first.
  if (isLoading) {
    return null;
  }

  // This is a convenience, not a control. The check runs on the device, and
  // the bundle is on the user's phone for anyone to unpack and change. What
  // protects data is the backend's permissions: the access token is what the
  // API checks, and a request without a valid one gets nothing back no matter
  // what this screen renders.
  const user = session?.user;

  if (!user) {
    return (
      <Redirect to={{ pathname: '/signin', params: { next: '/protected' } }} />
    );
  }

  return (
    <Screen>
      <Card>
        <CardHeader>
          <CardTitle>Protected</CardTitle>
          <CardDescription>
            Only a signed-in user gets this far.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <View className="gap-1">
            <Text className="text-neutral-500 text-sm">Email</Text>
            <Text className="text-neutral-900">{user.email ?? '—'}</Text>
          </View>
          <View className="gap-1">
            <Text className="text-neutral-500 text-sm">User id</Text>
            <Text className="font-mono text-neutral-900 text-xs">
              {user.id}
            </Text>
          </View>
          <SignOutButton />
        </CardContent>
      </Card>
    </Screen>
  );
}
