// examples/quickstarts/sveltekit/src/routes/auth/sign-in/email-password/+page.svelte
<script>
	import Button from '$lib/components/Button.svelte'
	import Input from '$lib/components/Input.svelte'
	
	/** @type {import('./$types').Actions} */
	export let form;
</script>

<svelte:head>
	<title>Sign In</title>
</svelte:head>

<h1 class="text-2xl font-semibold text-center">Sign In</h1>

{#if form?.error}
	<p class="mt-3 font-semibold text-center text-red-500">{form?.error}</p>
{/if}

<form class="max-w-xl mx-auto space-y-5" method='POST'>
	<Input label="Email" id="email" name="email" type="email" required />

	<Input
		label="Password"
		id="password"
		name="password"
		type="password"
		required
	/>

	<Button class='w-full' type="submit">Sign In</Button>
</form>

// examples/quickstarts/nextjs-server-components/src/app/auth/sign-in/email-password/page.tsx
'use client'

import { signIn } from '@actions'
import Input from '@components/input'
import SubmitButton from '@components/submit-button'
import { useState } from 'react'

export default function SignInWithEmailAndPassword() {
  const [error, setError] = useState('')

  async function handleSignIn(formData: FormData) {
    const response = await signIn(formData)

    if (response?.error) {
      setError(response.error)
    }
  }

  return (
    <div className="flex flex-col items-center">
      <h1 className="text-2xl font-semibold text-center">Sign in with email and password</h1>

      {error && <p className="mt-3 font-semibold text-center text-red-500">{error}</p>}

      <form className="w-full max-w-lg space-y-5" action={handleSignIn}>
        <Input label="Email" id="email" name="email" type="email" required />

        <Input label="Password" id="password" name="password" type="password" required />

        <SubmitButton type="submit" className="w-full">
          Sign in
        </SubmitButton>
      </form>
    </div>
  )
}
