// templates/svelte/frontend/src/routes/auth/oauth/+page.svelte
<script lang="ts">
import * as Card from '$lib/components/ui/card';
import { useAuth } from '$lib/nhost/auth.svelte';
import { appOrigin } from '$lib/nhost/env';
import { nextDestination } from '$lib/signin/next';
import OAuthButtons from './OAuthButtons.svelte';
import { providers } from './providers';

/**
 * Sign in with a provider account.
 *
 * This is a redirect, not a request: each button sends the browser to the
 * auth service, which does the provider round-trip and comes back to
 * `redirectTo` with a refresh token on the URL. That token is redeemed by
 * `lib/nhost/linkToken.ts` when the app loads again, so this page never sees
 * the callback.
 */
const auth = useAuth();
const next = $derived(nextDestination());

const links = $derived(
  providers.map(({ id, label }) => ({
    id,
    label,
    href: auth.nhost.auth.signInProviderURL(id, {
      redirectTo: appOrigin() + next,
    }),
  })),
);
</script>

<div class="mx-auto max-w-md">
  <Card.Root>
    <Card.Header>
      <Card.Title>GitHub or Google</Card.Title>
      <Card.Description>Sign in with a provider account.</Card.Description>
    </Card.Header>
    <Card.Content class="flex flex-col gap-4">
      <OAuthButtons {links} />
      <p class="text-muted-foreground text-sm">
        A provider only works once it is enabled in <code>nhost.toml</code>. The
        README's OAuth section has the callback URL and the config.
      </p>
      <a
        href="/signin"
        class="text-muted-foreground text-sm underline-offset-4 hover:underline"
      >
        Other ways to sign in
      </a>
    </Card.Content>
  </Card.Root>
</div>

// templates/react-native/frontend/src/app/auth/oauth/index.tsx
import type { NhostClient } from '@nhost/nhost-js';
import type { SignInProvider } from '@nhost/nhost-js/auth';
import * as WebBrowser from 'expo-web-browser';
import { useState } from 'react';
import { Text } from 'react-native';
import { Screen } from '@/components/Screen';
import { Button } from '@/components/ui/Button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/Card';
import { ErrorText } from '@/components/ui/ErrorText';
import { useGo } from '@/lib/navigation';
import { useAuth } from '@/lib/nhost/AuthProvider';
import { redeemLinkToken } from '@/lib/nhost/linkToken';
import { authRedirectURL } from '@/lib/nhost/redirect';

/**
 * The providers this screen offers. Adding one is a line here and a section in
 * `nhost.toml`; the button and the round-trip are the same for all of them.
 */
const providers = [
  { id: 'github', label: 'Continue with GitHub' },
  { id: 'google', label: 'Continue with Google' },
] as const satisfies ReadonlyArray<{ id: SignInProvider; label: string }>;

/**
 * Runs the provider round-trip and signs the user in.
 *
 * This is where native differs most from the web. A browser app sends the page
 * to the auth service and never sees the callback: it comes back as a fresh
 * page load with a token on the URL. There is no page to leave here, so the
 * app opens the system browser as a modal session instead and is handed the
 * callback URL when it closes. That URL carries the refresh token, which is
 * redeemed the same way a deep link's would be.
 *
 * `openAuthSessionAsync` is what makes it a session rather than just opening a
 * browser: it is tied to this app, so the callback comes straight back and the
 * user is returned to where they were.
 */
async function signInWithProvider(
  nhost: NhostClient,
  provider: SignInProvider,
  next: string,
): Promise<{ error?: string; success?: boolean }> {
  const returnTo = authRedirectURL(next);

  const authUrl = nhost.auth.signInProviderURL(provider, {
    redirectTo: returnTo,
  });

  try {
    const result = await WebBrowser.openAuthSessionAsync(authUrl, returnTo);

    // `dismiss` and `cancel` are the user closing the browser, which is not a
    // failure and has nothing to report.
    if (result.type !== 'success') {
      return {};
    }

    await redeemLinkToken(nhost, result.url);

    if (!nhost.getUserSession()) {
      return { error: 'That sign-in did not complete. Try again.' };
    }

    return { success: true };
  } catch (err) {
    console.error('Error signing in with a provider:', err);

    return { error: 'Could not reach the provider. Try again.' };
  }
}

import { useNext } from '@/signin/useNext';

export default function OAuthScreen() {
  const { nhost } = useAuth();
  const go = useGo();
  const next = useNext();

  const [pending, setPending] = useState<string | undefined>();
  const [error, setError] = useState<string | undefined>();

  const handlePress = async (id: (typeof providers)[number]['id']) => {
    setError(undefined);
    setPending(id);
    try {
      const result = await signInWithProvider(nhost, id, next);
      if (result.error) {
        setError(result.error);
        return;
      }

      if (result.success) {
        go.replace(next);
      }
    } finally {
      setPending(undefined);
    }
  };

  return (
    <Screen>
      <Card>
        <CardHeader>
          <CardTitle>GitHub or Google</CardTitle>
          <CardDescription>Sign in with a provider account.</CardDescription>
        </CardHeader>
        <CardContent>
          {providers.map(({ id, label }) => (
            <Button
              key={id}
              variant="outline"
              isPending={pending === id}
              disabled={pending !== undefined}
              onPress={() => void handlePress(id)}
            >
              {label}
            </Button>
          ))}

          {error ? <ErrorText>{error}</ErrorText> : null}

          <Text className="text-neutral-500 text-sm">
            A provider only works once it is enabled in nhost.toml, and the
            app's deep link has to be in auth.redirections.allowedUrls. The
            README's OAuth section has both.
          </Text>

          <Text
            accessibilityRole="link"
            className="text-neutral-500 text-sm underline"
            onPress={() => go.push('/signin')}
          >
            Other ways to sign in
          </Text>
        </CardContent>
      </Card>
    </Screen>
  );
}
